"""Location landing pages — Dubai communities and the wider UAE."""

AREAS = [
    dict(key="marina", name="Dubai Marina & JBR", slug="curtains-blinds-dubai-marina", dubai=True,
         intro="High-rise apartments in Dubai Marina and JBR have wide, full-height glass facing the water and the afternoon sun. Glare, heat and privacy from neighbouring towers are the everyday challenges we solve here.",
         homes="Mostly apartments and penthouses with floor-to-ceiling windows and balcony sliding doors.",
         picks=["wave", "sheer", "blackout", "motorized", "sunscreen", "zebra"]),
    dict(key="downtown", name="Downtown Dubai & Business Bay", slug="curtains-blinds-downtown-dubai-business-bay", dubai=True,
         intro="Downtown Dubai and Business Bay combine luxury residences with busy offices. Homes want a hotel-like finish; offices want glare-free screens and a professional look.",
         homes="Apartments, serviced residences and offices with large glazed façades.",
         picks=["motorized", "wave", "sunscreen", "logo", "blackout-roller", "vertical"]),
    dict(key="palm", name="Palm Jumeirah", slug="curtains-blinds-palm-jumeirah", dubai=True,
         intro="Villas and beachfront apartments on Palm Jumeirah live with bright sea light all day. Layered sheers and blackouts, and motorized tracks for large openings, are the popular choices here.",
         homes="Frond villas, shoreline apartments and penthouses with double-height glass.",
         picks=["motorized", "sheer", "wave", "american", "bamboo", "blackout"]),
    dict(key="jumeirah", name="Jumeirah & Umm Suqeim", slug="curtains-blinds-jumeirah-umm-suqeim", dubai=True,
         intro="The low-rise villa neighbourhoods of Jumeirah and Umm Suqeim suit classic tailored curtains for majlis and living rooms, with practical blinds for kitchens and studies.",
         homes="Independent villas with majlis, family living rooms and garden-facing windows.",
         picks=["pinch-pleat", "american", "roman-b", "wooden", "blackout", "kids"]),
    dict(key="hills", name="Dubai Hills & Arabian Ranches", slug="curtains-blinds-dubai-hills-arabian-ranches", dubai=True,
         intro="New family villas and townhouses in Dubai Hills Estate and Arabian Ranches often need every window dressed at once — from living rooms and bedrooms to kids rooms and studies.",
         homes="Villas and townhouses furnished room by room for families.",
         picks=["wave", "kids", "blackout", "zebra", "wooden", "roman-b"]),
    dict(key="jvc", name="JVC, JLT & Dubai South", slug="curtains-blinds-jvc-jlt", dubai=True,
         intro="Jumeirah Village Circle, JLT and the growing Dubai South communities are full of apartments and townhouses where smart, practical window solutions make the most of every room.",
         homes="Apartments and townhouses, including many new move-ins and rentals.",
         picks=["eyelet", "zebra", "blackout-roller", "wave", "vertical", "sheer"]),
    dict(key="deira", name="Deira & Bur Dubai", slug="curtains-blinds-deira-bur-dubai", dubai=True,
         intro="Our showroom is on Naif Road in Deira, so homes, shops, clinics and offices across Deira and Bur Dubai are right on our doorstep. Visit us to see fabrics, or ask us to come to you.",
         homes="Apartments, family homes, retail, clinics and commercial offices.",
         picks=["pinch-pleat", "vertical", "hospital", "logo", "aluminium", "beaded"]),
    dict(key="mirdif", name="Mirdif & Dubai Festival City", slug="curtains-blinds-mirdif-festival-city", dubai=True,
         intro="Family villas in Mirdif and waterfront homes in Dubai Festival City call for comfortable, easy-care curtains and blinds that handle daily family life.",
         homes="Family villas, townhouses and waterfront apartments.",
         picks=["american", "wave", "kids", "blackout", "roman-c", "bamboo"]),
    dict(key="abudhabi", name="Abu Dhabi", slug="curtains-blinds-abu-dhabi", dubai=False,
         intro="We take curtain and blind orders from homes and businesses in Abu Dhabi. Send your window sizes, photos and location on WhatsApp and we will advise on options and arrange the visit and installation.",
         homes="Villas, apartments and commercial projects across the capital.",
         picks=["wave", "motorized", "pinch-pleat", "blackout", "sunscreen", "hospital"]),
    dict(key="sharjah", name="Sharjah", slug="curtains-blinds-sharjah", dubai=False,
         intro="Sharjah is next door to our Deira showroom, which makes it easy to visit us for fabrics or to arrange measurement at your home or business.",
         homes="Family villas, apartments, schools, clinics and offices.",
         picks=["american", "pinch-pleat", "blackout", "zebra", "vertical", "kids"]),
    dict(key="ajman", name="Ajman", slug="curtains-blinds-ajman", dubai=False,
         intro="Homes and businesses in Ajman can order made-to-measure curtains and blinds from us. Share your requirements on WhatsApp and we will arrange the visit and installation.",
         homes="Apartments, villas and commercial spaces.",
         picks=["wave", "eyelet", "blackout-roller", "zebra", "vertical", "sheer"]),
    dict(key="rak", name="Ras Al Khaimah", slug="curtains-blinds-ras-al-khaimah", dubai=False,
         intro="From beachfront villas to hotels and offices, we supply curtains and blinds to Ras Al Khaimah. Send photos and sizes on WhatsApp to plan your project.",
         homes="Villas, resort apartments, hotels and offices.",
         picks=["sheer", "blackout", "bamboo", "motorized", "sunscreen", "wave"]),
    dict(key="alain", name="Al Ain", slug="curtains-blinds-al-ain", dubai=False,
         intro="Al Ain's strong inland sun makes good heat and light control essential. We supply made-to-measure curtains and blinds for villas and businesses in Al Ain.",
         homes="Family villas, farms and commercial buildings.",
         picks=["blackout", "pinch-pleat", "american", "wooden", "sunscreen", "roman-b"]),
]
