"""Product page copy — one entry per Drive product folder.

Copy describes each product type in general, accurate terms. It makes no
claims about prices, delivery times, warranty periods or project counts.
"""
from data import (WAVE, WAVE_INSTALL, PINCH, EYELET, AMERICAN, ROMAN_C, BEADED, CINEMA, KIDS,
                  HOSPITAL, LOGO_BLINDS, PRINTED, ZEBRA, VERTICAL, WOODEN, ALU, BAMBOO, ROMAN_B,
                  SUNSCREEN, BLACKOUT_ROLLER, PROJECTS)

CURTAINS = [
    dict(
        key="wave", label="Wave Curtains", slug="wave-curtains",
        title="Wave Curtains in Dubai", h1="Wave curtains, <em>made to measure</em>",
        desc="Made-to-measure wave curtains in Dubai: soft, even S-folds on a ceiling or wall track. Free home visit and professional installation. WhatsApp +971 50 859 9803.",
        lead="Soft, continuous S-shaped folds that stack neatly to the side — the modern standard for living rooms, bedrooms and floor-to-ceiling glass.",
        intro=["Wave curtains hang from carriers spaced evenly along a track, so the fabric falls into identical rolling folds from end to end. The result is a calm, tailored look that suits contemporary apartments and villas alike.",
               "We measure your windows, help you choose sheer, dim-out or blackout fabric, then stitch and install the curtains together with the track — ceiling-mounted or on the wall."],
        features=["Uniform S-folds that stay in shape", "Ceiling or wall-mounted tracks", "Works with sheer, dim-out and blackout fabrics", "Hand-drawn, cord-operated or motorized", "Double-track option for sheer + blackout layers"],
        best=["Living rooms and majlis", "Floor-to-ceiling windows and sliding doors", "Bedrooms that need a sheer and blackout combination"],
        imgs=WAVE + WAVE_INSTALL,
        faq=[("Can wave curtains be motorized?", "Yes. Wave curtains run on a track, so the same heading can be fitted with a motorized track and remote or smart-home control. See our motorized curtains page for details."),
             ("Can I combine sheer and blackout wave curtains?", "Yes — a double track lets you hang a sheer layer for daytime privacy and a blackout layer for sleep, each operated independently."),
             ("Do you install the track as well?", "Yes. Our team supplies and installs the track and the curtains during the same visit once your order is ready.")],
        related=["pinch-pleat", "motorized", "blackout", "sheer"],
    ),
    dict(
        key="pinch-pleat", label="Pinch Pleat Curtains", slug="pinch-pleat-curtains",
        title="Pinch Pleat Curtains in Dubai", h1="Pinch pleat curtains, <em>classically tailored</em>",
        desc="Custom pinch pleat curtains in Dubai — tailored pleats for formal living rooms, majlis and bedrooms. Free home visit and installation. WhatsApp +971 50 859 9803.",
        lead="Hand-gathered pleats at the heading give a structured, formal drape that suits classic and transitional interiors.",
        intro=["Pinch pleat curtains are gathered into evenly spaced clusters of folds at the top, giving the fabric a crisp, tailored fall. The pleats hold their shape whether the curtains are open or drawn.",
               "They hang from rings on a decorative rod or from hooks on a track, and pair well with heavier fabrics such as velvets, linens and lined blackout cloths."],
        features=["Double or triple pleat headings", "Rod-and-ring or track mounting", "Lined, interlined or blackout options", "Suits heavy, luxurious fabrics", "Tie-backs and trims available on request"],
        best=["Formal living and dining rooms", "Majlis and reception areas", "Classic villas and bedrooms"],
        imgs=PINCH,
        faq=[("What is the difference between pinch pleat and wave curtains?", "Pinch pleats are gathered into tailored clusters at the heading for a formal look; wave curtains form soft continuous S-folds for a modern look."),
             ("Can pinch pleat curtains be blackout?", "Yes — we can add a blackout lining or use a blackout fabric so the room darkens fully.")],
        related=["wave", "american", "eyelet", "blackout"],
    ),
    dict(
        key="eyelet", label="Eyelet Curtains", slug="eyelet-curtains",
        title="Eyelet Curtains in Dubai", h1="Eyelet curtains, <em>easy and contemporary</em>",
        desc="Made-to-measure eyelet (grommet) curtains in Dubai with metal rings on a curtain rod. Free home visit, fabric samples and installation. WhatsApp +971 50 859 9803.",
        lead="Metal rings punched into the heading slide straight onto a curtain rod for deep, even folds and effortless opening.",
        intro=["Eyelet curtains — also called grommet curtains — have rings set into the top hem that thread directly onto a pole. They glide smoothly, fold deeply and give a relaxed, contemporary finish.",
               "Choose the ring finish to match your rod and hardware, and pair them with sheer, dim-out or blackout fabrics depending on the room."],
        features=["Rings in several finishes to match your rod", "Deep, even folds", "Smooth, easy opening by hand", "Sheer to blackout fabrics", "Rod supply and installation"],
        best=["Bedrooms and children's rooms", "Apartments and rental homes", "Casual living spaces"],
        imgs=EYELET,
        faq=[("Do eyelet curtains need a rod or a track?", "Eyelet curtains are made for a curtain rod (pole). If you prefer a track, wave or pinch pleat headings are better choices."),
             ("Can you supply the curtain rod?", "Yes — we can supply and install the rod together with your curtains.")],
        related=["wave", "kids", "blackout", "sheer"],
    ),
    dict(
        key="american", label="American Style Curtains", slug="american-style-curtains",
        title="American Style Curtains in Dubai", h1="American style curtains, <em>full and elegant</em>",
        desc="American style curtains in Dubai — full, generous drapes with a tailored heading for elegant homes. Made to measure and installed. WhatsApp +971 50 859 9803.",
        lead="Generous, full-length drapes with a tailored heading — a timeless look for living rooms, bedrooms and villas.",
        intro=["American style curtains are known for their fullness: plenty of fabric, a neatly finished heading and long drops that pool gently or just kiss the floor.",
               "We tailor the fullness, lining and length to your windows, and install them on a track or decorative rod."],
        features=["Generous fullness for a luxurious drape", "Floor-length or puddled finishes", "Lined, blackout or sheer layers", "Track or rod mounting", "Coordinated sheers and tie-backs"],
        best=["Villas and large living rooms", "Master bedrooms", "Double-height windows"],
        imgs=AMERICAN + [PROJECTS[8], PROJECTS[15], PROJECTS[18]],
        faq=[("How are American style curtains different from pinch pleat?", "Both are tailored headings. American style focuses on fullness and a softer, generous drape; pinch pleats have distinct, structured pleat clusters."),
             ("Can you match curtains across several rooms?", "Yes — we can use the same fabric and heading throughout your home for a consistent look.")],
        related=["pinch-pleat", "wave", "sheer", "blackout"],
    ),
    dict(
        key="roman-c", label="Roman Curtains", slug="roman-curtains",
        title="Roman Curtains in Dubai", h1="Roman curtains, <em>soft folds that lift</em>",
        desc="Made-to-measure Roman style curtains (Roman shades) in Dubai — fabric panels that lift into neat horizontal folds. Free home visit. WhatsApp +971 50 859 9803.",
        lead="A single fabric panel that raises into neat horizontal folds — the softness of a curtain with the compact footprint of a blind.",
        intro=["Roman curtains, often called Roman shades, are made from your chosen fabric and lift into layered horizontal folds when raised. They sit inside or just outside the window frame, leaving the wall clear.",
               "They are ideal where full-length curtains would crowd the room — kitchens, study rooms, bay windows — and can be layered under side curtains for a finished look."],
        features=["Flat or relaxed fold styles", "Any curtain fabric, lined or blackout", "Chain, cordless or motorized operation", "Inside- or outside-recess fitting", "Can be layered with dress curtains"],
        best=["Kitchens and study rooms", "Bay and small windows", "Bedrooms that need a neat blackout"],
        imgs=ROMAN_C,
        faq=[("Are Roman curtains the same as Roman blinds?", "They work the same way. We use 'Roman curtains' for softer, fabric-led designs and cover practical options on our Roman blinds page."),
             ("Can Roman curtains be blackout?", "Yes, we can add a blackout lining behind your chosen fabric.")],
        related=["roman-b", "wave", "blackout", "kids"],
    ),
    dict(
        key="blackout", label="Blackout Curtains", slug="blackout-curtains",
        title="Blackout Curtains in Dubai", h1="Blackout curtains, <em>for deep, cool rest</em>",
        desc="Blackout curtains in Dubai for bedrooms, offices and media rooms — block strong sunlight and heat. Made to measure with free home visit. WhatsApp +971 50 859 9803.",
        lead="Block out Dubai's strong sun for better sleep, cooler rooms and screen-friendly offices.",
        intro=["Blackout curtains use tightly woven or coated fabrics — or a separate blackout lining — to stop light passing through. In the UAE they also help keep rooms cooler by reducing solar heat through the glass.",
               "Any of our headings can be made in blackout: wave, pinch pleat, eyelet or American style. For the best result we extend the curtains past the window edges and, where possible, use a ceiling track."],
        features=["Blackout fabric or blackout lining", "Available in every heading style", "Pairs with a sheer on a double track", "Helps reduce heat and glare", "Motorized option for large windows"],
        best=["Bedrooms and nurseries", "Home cinemas and media rooms", "Offices and meeting rooms facing the sun"],
        imgs=[], existing=["blackout-bedroom", "blackout-office"],
        faq=[("Do blackout curtains make a room completely dark?", "They block the light through the fabric. Some light can still come around the edges, so we extend the curtains beyond the window and use a ceiling track where possible."),
             ("Can I have a sheer and a blackout together?", "Yes — a double track lets you use the sheer during the day and the blackout at night.")],
        related=["wave", "sheer", "motorized", "blackout-roller"],
    ),
    dict(
        key="sheer", label="Sheer Curtains", slug="sheer-curtains",
        title="Sheer Curtains in Dubai", h1="Sheer curtains, <em>light made soft</em>",
        desc="Sheer curtains in Dubai that filter daylight and keep daytime privacy. Linen-look, voile and textured sheers, made to measure. WhatsApp +971 50 859 9803.",
        lead="Filter bright daylight, soften the view and keep daytime privacy without darkening the room.",
        intro=["Sheer curtains are lightweight, translucent fabrics that diffuse sunlight and reduce glare while keeping the room bright. From the outside they make it harder to see in during the day.",
               "They are most often paired with a blackout layer on a double track, giving you a soft daytime look and full darkness at night."],
        features=["Voile, linen-look and textured sheers", "Wave or pinch pleat headings", "Double-track pairing with blackout", "Softens glare on screens and floors", "Motorized option"],
        best=["Living rooms with big glass", "Apartments with close neighbours", "Layering with blackout in bedrooms"],
        imgs=[], existing=["sheer-living", "sheer-bedroom"],
        faq=[("Do sheer curtains give privacy at night?", "Not fully — with lights on inside, sheers become see-through. Pair them with a blackout or dim-out layer for night-time privacy."),
             ("Which heading works best for sheers?", "Wave headings are the most popular for sheers because they create even, flowing folds.")],
        related=["wave", "blackout", "motorized", "american"],
    ),
    dict(
        key="motorized", label="Motorized Curtains", slug="motorized-curtains",
        title="Motorized Curtains in Dubai", h1="Motorized curtains, <em>at the touch of a button</em>",
        desc="Motorized and smart curtains in Dubai — remote, wall switch or smart-home control for wave and pinch pleat curtains. Free home visit. WhatsApp +971 50 859 9803.",
        lead="Open and close your curtains by remote, wall switch or smart-home app — ideal for wide glass, high windows and modern homes.",
        intro=["A motorized curtain uses an electric track that draws the fabric for you. It is especially practical for very wide or double-height windows, and for layered sheer and blackout setups.",
               "We plan the track, motor position and power point during the home visit, then install and set up the controls. Tell us if you use a smart-home system so we can advise on compatibility."],
        features=["Remote, wall switch or app control", "Suits wave and pinch pleat headings", "Separate control for sheer and blackout tracks", "Ideal for wide and high windows", "Neat ceiling or wall installation"],
        best=["Villas and penthouses", "Double-height and corner windows", "Smart homes and home cinemas"],
        imgs=[], existing=["motor-hall", "motor-bedroom"],
        faq=[("Do motorized curtains need a power point?", "Yes, the motor needs power near the end of the track. We check this during the home visit and advise on the best position."),
             ("Can existing curtains be motorized?", "It depends on the fabric and heading. Send us photos on WhatsApp and we will advise.")],
        related=["wave", "blackout", "sheer", "cinema"],
    ),
    dict(
        key="beaded", label="Beaded Curtains", slug="beaded-curtains",
        title="Beaded Curtains in Dubai", h1="Beaded curtains, <em>decor that moves</em>",
        desc="Beaded curtains in Dubai for doorways, partitions and decorative windows — glass, crystal-look and wooden bead styles. WhatsApp +971 50 859 9803 to order.",
        lead="Strands of beads that divide a space, catch the light and add movement — for doorways, partitions and feature windows.",
        intro=["Beaded curtains are made from hanging strands of beads that let light and air through while visually separating a space. They are popular as room dividers, doorway features and decorative window dressings.",
               "Share the opening size and the look you want on WhatsApp and we will suggest suitable bead styles and colours."],
        features=["Room dividers and doorway curtains", "Glass, crystal-look and wooden bead styles", "Made to your opening size", "Decorative for homes, salons and retail", "Easy to install on a rail"],
        best=["Doorways and arches", "Open-plan partitions", "Boutiques, salons and events"],
        imgs=BEADED,
        faq=[("Can beaded curtains be made to size?", "Yes — send us the width and height of the opening and we will advise on the options."),
             ("Are beaded curtains suitable for windows?", "They are mostly decorative and do not block light or give full privacy, so they are best for doorways, partitions and feature windows.")],
        related=["kids", "sheer", "cinema", "wave"],
    ),
    dict(
        key="cinema", label="Cinema Curtains", slug="cinema-curtains",
        title="Cinema & Home Theatre Curtains in Dubai", h1="Cinema curtains, <em>for the full theatre feel</em>",
        desc="Cinema and home theatre curtains in Dubai — heavy, light-blocking drapes for screens, stages and media rooms. Made to measure. WhatsApp +971 50 859 9803.",
        lead="Heavy, rich drapes that darken the room and frame the screen — for home cinemas, media rooms and stages.",
        intro=["Cinema curtains use dense, light-blocking fabrics with generous fullness to create darkness and a theatrical finish around a screen or stage.",
               "They can be fitted on a ceiling track and motorized so they open as the film starts. Tell us about your room and we will recommend the right fabric and track."],
        features=["Heavy, light-blocking fabrics", "Generous fullness for a theatre drape", "Screen framing and wall-to-wall coverage", "Motorized opening available", "Made to your room size"],
        best=["Home cinemas and media rooms", "Auditoriums and stages", "Hotel and event spaces"],
        imgs=CINEMA,
        faq=[("Can cinema curtains be motorized?", "Yes — a motorized ceiling track is a popular choice so the curtains open and close from your remote."),
             ("Which fabric is best for a home cinema?", "Dense, dark fabrics such as velvets or blackout-lined cloths work best. We bring samples to the home visit.")],
        related=["motorized", "blackout", "pinch-pleat", "wave"],
    ),
    dict(
        key="kids", label="Kids Curtains", slug="kids-curtains",
        title="Kids Room Curtains in Dubai", h1="Kids curtains, <em>playful and practical</em>",
        desc="Kids room curtains in Dubai — playful prints and colours with blackout options for better naps. Made to measure and installed. WhatsApp +971 50 859 9803.",
        lead="Cheerful prints and colours for nurseries and children's rooms — with blackout options for daytime naps.",
        intro=["Children's rooms need curtains that look fun and work hard. We offer printed and plain fabrics in playful colours, and can add a blackout lining so naps are easier.",
               "Cordless headings such as eyelet and wave keep things simple, and matching blinds are available for a coordinated look."],
        features=["Printed and colourful fabrics", "Blackout lining for naps", "Cordless eyelet and wave headings", "Coordinating blinds available", "Made to measure and installed"],
        best=["Nurseries", "Children's bedrooms and playrooms", "Teen rooms"],
        imgs=KIDS,
        faq=[("Can kids curtains be blackout?", "Yes — we add a blackout lining behind the printed fabric."),
             ("Do you have cordless options?", "Yes. Eyelet and wave curtains are hand-drawn with no loose cords.")],
        related=["eyelet", "blackout", "printed", "roman-c"],
    ),
    dict(
        key="hospital", label="Hospital Curtains", slug="hospital-curtains",
        title="Hospital Cubicle Curtains in Dubai", h1="Hospital curtains, <em>privacy for patient care</em>",
        desc="Hospital cubicle and privacy curtains in Dubai for clinics and healthcare facilities, with ceiling tracks and installation. WhatsApp +971 50 859 9803.",
        lead="Cubicle and privacy curtains with ceiling tracks for hospitals, clinics and medical centres.",
        intro=["Hospital curtains divide wards and treatment rooms into private bays. They run on ceiling-mounted cubicle tracks and are typically made with a mesh top section to let air and light through.",
               "We supply and install curtains and tracks for clinics and healthcare projects. Share your floor plan or bay sizes on WhatsApp for a quotation."],
        features=["Cubicle curtains with mesh tops", "Ceiling-mounted cubicle tracks", "Sized to each bed bay", "Easy-to-clean fabrics", "Supply and installation for projects"],
        best=["Hospitals and wards", "Clinics and medical centres", "Treatment and examination rooms"],
        imgs=HOSPITAL, existing=["hospital-room"],
        faq=[("Do you supply the cubicle tracks?", "Yes — we supply and install the ceiling tracks together with the curtains."),
             ("Can you handle a full facility?", "Yes. Send the drawings or bay sizes and we will prepare a project quotation.")],
        related=["logo", "blackout-roller", "vertical", "sunscreen"],
    ),
]

BLINDS = [
    dict(
        key="blackout-roller", label="Blackout Roller Blinds", slug="blackout-roller-blinds",
        title="Blackout Roller Blinds in Dubai", h1="Blackout roller blinds, <em>simple and dark</em>",
        desc="Blackout roller blinds in Dubai for bedrooms, offices and media rooms. Made to measure with chain or motorized operation. WhatsApp +971 50 859 9803.",
        lead="A clean roll of blackout fabric that disappears into a slim cassette or roller when raised.",
        intro=["Roller blinds are one of the simplest and neatest window treatments. With a blackout fabric they block light for sleep, screens and presentations.",
               "They fit inside the window recess or on the wall, and can be operated by chain or motor. They also pair well with curtains for a layered look."],
        features=["Blackout roller fabrics in many colours", "Chain or motorized operation", "Inside or outside recess fitting", "Can be layered under curtains", "Easy to clean"],
        best=["Bedrooms", "Offices and meeting rooms", "Media rooms"],
        imgs=BLACKOUT_ROLLER,
        faq=[("Can roller blinds be motorized?", "Yes, roller blinds can be fitted with a motor and remote control."),
             ("Can I combine a blackout and a sunscreen roller?", "Yes — a double roller bracket holds a sunscreen and a blackout blind together, or consider zebra blinds.")],
        related=["sunscreen", "zebra", "blackout", "roman-b"],
    ),
    dict(
        key="sunscreen", label="Sunscreen Roller Blinds", slug="sunscreen-roller-blinds",
        title="Sunscreen Roller Blinds in Dubai", h1="Sunscreen roller blinds, <em>keep the view, cut the glare</em>",
        desc="Sunscreen roller blinds in Dubai reduce glare and heat while keeping your view. Ideal for offices and glass façades. WhatsApp +971 50 859 9803.",
        lead="Perforated sunscreen fabric cuts glare and heat while you keep the view outside.",
        intro=["Sunscreen blinds are made from an openly woven fabric that filters sunlight. You can still see out, but glare on screens is reduced and less heat builds up inside.",
               "They are a favourite for offices, apartments with large glazing and anywhere the view matters."],
        features=["Filters glare and solar heat", "Keeps the outside view", "Chain or motorized operation", "Works well on large glazing", "Can carry a printed logo"],
        best=["Offices and co-working spaces", "Apartments with big windows", "Showrooms and receptions"],
        imgs=SUNSCREEN,
        faq=[("Do sunscreen blinds give privacy at night?", "No — at night with lights on inside, sunscreen fabric becomes see-through. Add a blackout blind or curtain for night privacy."),
             ("Can you print our logo on sunscreen blinds?", "Yes — see our customized logo blinds page.")],
        related=["logo", "blackout-roller", "zebra", "vertical"],
    ),
    dict(
        key="zebra", label="Zebra Blinds", slug="zebra-blinds",
        title="Zebra Blinds in Dubai", h1="Zebra blinds, <em>day and night in one</em>",
        desc="Zebra (day & night / duplex) blinds in Dubai — alternating sheer and solid bands for adjustable light and privacy. Made to measure. WhatsApp +971 50 859 9803.",
        lead="Alternating sheer and solid bands slide past each other so you can dial light and privacy up or down.",
        intro=["Zebra blinds — also called day & night or duplex blinds — have two layers of striped fabric. Line the solid bands up for privacy, or align the sheer bands to let light in.",
               "They combine the tidiness of a roller blind with the adjustability of a venetian, and come in many colours and textures."],
        features=["Adjustable light and privacy", "Sheer and solid alternating bands", "Cassette options for a neat finish", "Chain or motorized", "Wide colour range"],
        best=["Living rooms and bedrooms", "Home offices", "Apartments"],
        imgs=ZEBRA,
        faq=[("What is the difference between zebra and roller blinds?", "A roller blind is one fabric; a zebra blind has two striped layers you can offset to control light and privacy."),
             ("Are zebra blinds blackout?", "Some zebra fabrics have dim-out or blackout solid bands. Ask us for samples.")],
        related=["blackout-roller", "sunscreen", "vertical", "wooden"],
    ),
    dict(
        key="roman-b", label="Roman Blinds", slug="roman-blinds",
        title="Roman Blinds in Dubai", h1="Roman blinds, <em>tailored fabric folds</em>",
        desc="Made-to-measure Roman blinds in Dubai in hundreds of fabrics — lined or blackout, chain or motorized. Free home visit and installation. WhatsApp +971 50 859 9803.",
        lead="Fabric blinds that stack into tidy horizontal folds — the warmth of fabric with the neatness of a blind.",
        intro=["Roman blinds are made from curtain fabric with rods sewn in at intervals, so the blind folds up evenly as it rises. They bring texture and pattern to the window without the bulk of full curtains.",
               "Choose any fabric from our catalogues, add a blackout lining if needed, and pick chain or motorized operation."],
        features=["Any fabric from our catalogues", "Lined, dim-out or blackout", "Chain or motorized", "Inside or outside recess", "Coordinate with curtains and cushions"],
        best=["Kitchens and dining rooms", "Bedrooms and nurseries", "Studies and small windows"],
        imgs=ROMAN_B,
        faq=[("How do I choose between Roman blinds and curtains?", "Roman blinds suit smaller windows and tight spaces; curtains suit wide windows and a softer, fuller look. Many rooms combine both."),
             ("Can I see fabrics before ordering?", "Yes — browse the catalogue page, then we bring samples to your home visit.")],
        related=["roman-c", "blackout-roller", "bamboo", "wooden"],
    ),
    dict(
        key="vertical", label="Vertical Blinds", slug="vertical-blinds",
        title="Vertical Blinds in Dubai", h1="Vertical blinds, <em>practical for wide glass</em>",
        desc="Vertical blinds in Dubai for offices, sliding doors and wide windows — rotating fabric slats for easy light control. Made to measure. WhatsApp +971 50 859 9803.",
        lead="Vertical slats that tilt and draw aside — a practical, budget-friendly choice for wide windows and sliding doors.",
        intro=["Vertical blinds are made of individual slats hanging from a headrail. The slats rotate to control light and draw to one side to open the window.",
               "They are especially practical for offices, patio doors and large windows, and are easy to maintain."],
        features=["Rotating slats for light control", "Stacks neatly to one or both sides", "Suits sliding and patio doors", "Blackout and light-filtering fabrics", "Easy maintenance"],
        best=["Offices and commercial spaces", "Sliding and patio doors", "Wide windows"],
        imgs=VERTICAL,
        faq=[("Are vertical blinds good for sliding doors?", "Yes — they draw aside easily so you can walk through, and tilt for light control."),
             ("Can individual slats be replaced?", "Generally yes. Contact us on WhatsApp with a photo and we will advise.")],
        related=["sunscreen", "zebra", "aluminium", "hospital"],
    ),
    dict(
        key="wooden", label="Wooden Blinds", slug="wooden-blinds",
        title="Wooden Venetian Blinds in Dubai", h1="Wooden blinds, <em>natural warmth</em>",
        desc="Wooden venetian blinds in Dubai with 25 mm and 50 mm slats — warm, natural light control for homes and offices. Made to measure. WhatsApp +971 50 859 9803.",
        lead="Real-wood venetian slats in 25 mm and 50 mm widths — natural warmth with precise light control.",
        intro=["Wooden venetian blinds tilt to direct light exactly where you want it and raise fully to clear the window. The natural grain adds warmth to living rooms, studies and bedrooms.",
               "Choose 50 mm slats for a bold, contemporary look or 25 mm slats for smaller windows, in a range of wood tones, with cords or ladder tapes."],
        features=["25 mm and 50 mm slat widths", "Range of wood tones and finishes", "Tilt for precise light control", "Cord or decorative ladder tape", "Inside or outside recess"],
        best=["Living rooms and studies", "Bedrooms", "Offices and receptions"],
        imgs=WOODEN,
        faq=[("Which slat size should I choose?", "50 mm slats suit larger windows and give a bolder look; 25 mm slats suit smaller windows and a finer look."),
             ("Are wooden blinds suitable for kitchens and bathrooms?", "For humid areas we usually recommend aluminium or faux-wood alternatives. Ask us for advice.")],
        related=["aluminium", "bamboo", "roman-b", "zebra"],
    ),
    dict(
        key="aluminium", label="Aluminium Venetian Blinds", slug="aluminium-venetian-blinds",
        title="Aluminium Venetian Blinds in Dubai", h1="Aluminium venetian blinds, <em>slim and durable</em>",
        desc="Aluminium venetian blinds (25 mm) in Dubai — slim, durable slats for kitchens, bathrooms and offices. Made to measure. WhatsApp +971 50 859 9803.",
        lead="Slim 25 mm aluminium slats that tilt for light control — durable, easy to clean and suited to busy spaces.",
        intro=["Aluminium venetian blinds are light, strong and moisture-tolerant, making them a practical choice for kitchens, bathrooms and offices.",
               "They are available in many colours, including metallic and perforated finishes, and fit neatly inside the window recess."],
        features=["25 mm aluminium slats", "Many colours and finishes", "Perforated options available", "Moisture-tolerant and easy to clean", "Inside recess fitting"],
        best=["Kitchens and bathrooms", "Offices", "Small windows"],
        imgs=ALU,
        faq=[("Are aluminium blinds good for bathrooms?", "Yes — aluminium handles humidity well and wipes clean easily."),
             ("Can aluminium blinds be made in custom colours?", "They come in a wide colour range; share your preference and we will send options.")],
        related=["wooden", "vertical", "zebra", "sunscreen"],
    ),
    dict(
        key="bamboo", label="Bamboo Blinds", slug="bamboo-blinds",
        title="Bamboo Blinds in Dubai", h1="Bamboo blinds, <em>natural texture</em>",
        desc="Bamboo blinds in Dubai — roller and Roman styles for indoor rooms, balconies and outdoor seating. Natural texture, made to measure. WhatsApp +971 50 859 9803.",
        lead="Natural woven bamboo in roller and Roman styles — for relaxed interiors, balconies and outdoor seating.",
        intro=["Bamboo blinds bring an organic, textured look and soft filtered light. They suit coastal, bohemian and resort-style interiors.",
               "Indoor versions come as roller or Roman blinds; outdoor versions shade balconies, terraces and garden seating."],
        features=["Natural woven bamboo", "Roller and Roman styles", "Indoor and outdoor versions", "Soft filtered light", "Optional privacy lining"],
        best=["Living rooms and sunrooms", "Balconies and terraces", "Cafés and restaurants"],
        imgs=BAMBOO,
        faq=[("Can bamboo blinds be used outdoors?", "Yes, we offer outdoor bamboo blinds for balconies and terraces."),
             ("Do bamboo blinds give privacy?", "The natural weave filters light; add a lining if you need more privacy.")],
        related=["wooden", "roman-b", "sunscreen", "beaded"],
    ),
    dict(
        key="printed", label="Printed Blinds", slug="printed-blinds",
        title="Custom Printed Blinds in Dubai", h1="Printed blinds, <em>your image on the window</em>",
        desc="Custom printed roller blinds in Dubai — print photos, patterns or artwork on your blinds for homes, kids rooms and businesses. WhatsApp +971 50 859 9803.",
        lead="Turn a window into a feature: photos, patterns or artwork printed onto roller blinds.",
        intro=["Printed blinds let you put any design on the window — a landscape, a pattern, artwork for a child's room or a brand graphic for a business.",
               "Send us your image or choose from designs, and we will advise on the right fabric and size. See the Custom Print on Fabric catalogue for ideas."],
        features=["Photos, patterns and artwork", "Roller blind format", "Blackout or light-filtering base fabrics", "Great for kids rooms and feature walls", "Business branding options"],
        best=["Kids rooms", "Feature windows", "Shops, cafés and offices"],
        imgs=PRINTED,
        faq=[("What image quality do you need?", "A high-resolution image works best. Send it on WhatsApp and we will check it before printing."),
             ("Can printed blinds be blackout?", "Yes — we can print on blackout or light-filtering fabric.")],
        related=["logo", "kids", "blackout-roller", "sunscreen"],
    ),
    dict(
        key="logo", label="Logo Sunscreen Blinds", slug="logo-sunscreen-blinds",
        title="Customised Logo Sunscreen Blinds in Dubai", h1="Logo sunscreen blinds, <em>shade that carries your brand</em>",
        desc="Customised logo sunscreen and roller blinds in Dubai for offices, shops and showrooms — branded shade with glare control. WhatsApp +971 50 859 9803.",
        lead="Sunscreen and roller blinds printed with your logo — glare control that also puts your brand on the glass.",
        intro=["Branded blinds turn shop fronts, office windows and receptions into brand touchpoints while controlling glare and heat.",
               "Send us your logo files and window sizes on WhatsApp and we will prepare a proposal."],
        features=["Logo printed on sunscreen or roller fabric", "Glare and heat control", "Shop fronts, offices and receptions", "Chain or motorized", "Consistent branding across branches"],
        best=["Offices and receptions", "Shops and showrooms", "Clinics and restaurants"],
        imgs=LOGO_BLINDS,
        faq=[("What file do you need for the logo?", "A vector file (AI, EPS, PDF or SVG) or a high-resolution PNG works best."),
             ("Can you do several branches?", "Yes — we can produce matching branded blinds for multiple locations.")],
        related=["printed", "sunscreen", "vertical", "hospital"],
    ),
]

ALL_PRODUCTS = CURTAINS + BLINDS
PRODUCT_BY_KEY = {p["key"]: p for p in ALL_PRODUCTS}
