<?php
/**
 * Casa Vera Home interior services: 6 category pages (curtains, carpets,
 * wallpaper, blinds, upholstery, flooring) and their 40 sub-pages.
 *
 * Existing pages with these slugs (from the previous site) are adopted:
 * moved under their category and rebuilt in this theme's layout. The old
 * content stays available in each page's Revisions.
 *
 * @package DGF
 */

defined( 'ABSPATH' ) || exit;

/**
 * Category + sub-page definitions, merged into dgf_pages_data().
 *
 * @return array<string,array>
 */
function dgf_interiors_data() {
	$b = static function ( $h, $t ) {
		return array( $h, $t );
	};

	$categories = array(
		'curtains'   => array(
			'title'     => 'Curtains',
			'excerpt'   => 'Made-to-measure blackout, sheer and motorised curtains — measured, stitched and installed across Dubai and the UAE by Casa Vera Home.',
			'seo_title' => 'Curtains Dubai | Blackout, Sheer & Motorised Curtains',
			'seo_desc'  => 'Made-to-measure curtains in Dubai & UAE: blackout, sheer, motorised and office curtains with rods and tracks. Free measurement. Quote on WhatsApp.',
			'keyword'   => 'curtains dubai',
			'intro'     => 'From light-filtering sheers to full blackout and motorised tracks, every curtain is made to measure for your windows and fitted by our own team.',
			'children'  => array(
				'blackout-curtains'            => array(
					'title'     => 'Blackout Curtains',
					'excerpt'   => 'Lined curtains that block light and heat — perfect for bedrooms, media rooms and west-facing windows in the UAE sun.',
					'seo_title' => 'Blackout Curtains Dubai | Made to Measure & Installed',
					'seo_desc'  => 'Blackout curtains in Dubai: thermal-lined, made to measure and installed. Block light and heat in bedrooms and media rooms. Quote on WhatsApp.',
					'keyword'   => 'blackout curtains dubai',
					'intro'     => array( 'Blackout curtains use a tightly woven or lined fabric that stops daylight coming through, so bedrooms stay dark for sleep and living rooms stay cooler in the afternoon sun.', 'We measure every window, help you choose fabric and colour, and fit them on rods or tracks with the right stack-back so they close fully.' ),
					'benefits'  => array( $b( 'Deep sleep', 'Keeps bedrooms dark for day sleepers, children and shift workers.' ), $b( 'Cooler rooms', 'Thermal linings reduce heat gain from strong UAE sun.' ), $b( 'Privacy', 'Nothing visible from outside, day or night.' ), $b( 'Made to measure', 'Tailored widths and drops for a clean, finished look.' ) ),
					'specs'     => array( 'Full blackout or dim-out fabrics', 'Thermal and acoustic lining options', 'Pinch pleat, wave and eyelet headings', 'Fitted on rods, tracks or motorised systems' ),
					'uses'      => array( 'Bedrooms and nurseries', 'Home cinemas and media rooms', 'Hotel and serviced apartments', 'West-facing living rooms' ),
					'faqs'      => array( array( 'Do blackout curtains block 100% of light?', 'The fabric itself can block almost all light; small gaps at the sides and top are reduced with wrap-around rods, ceiling tracks and correct overlap.' ), array( 'Can I combine blackout with sheer curtains?', 'Yes. A double track lets you use sheers during the day and blackout at night.' ), array( 'How long does it take?', 'After measurement and fabric selection we confirm the stitching time on WhatsApp, then install in a single visit.' ) ),
				),
				'sheer-curtains'               => array(
					'title'     => 'Sheer Curtains',
					'excerpt'   => 'Light, airy sheers that soften daylight and add privacy without darkening the room.',
					'seo_title' => 'Sheer Curtains Dubai | Voile & Linen-Look Sheers',
					'seo_desc'  => 'Sheer curtains in Dubai: voile and linen-look sheers made to measure, alone or layered with blackout. Free measurement. Quote on WhatsApp.',
					'keyword'   => 'sheer curtains dubai',
					'intro'     => array( 'Sheer curtains filter bright light into a soft glow, cut glare on screens and give daytime privacy while keeping views and brightness.', 'They work beautifully on their own or layered in front of blackout curtains on a double track.' ),
					'benefits'  => array( $b( 'Soft daylight', 'Diffuses harsh sun without making the room dark.' ), $b( 'Daytime privacy', 'Hard to see through from outside in daylight.' ), $b( 'Elegant look', 'Floor-length sheers make ceilings feel higher.' ), $b( 'Easy to layer', 'Pairs with blackout curtains or blinds.' ) ),
					'specs'     => array( 'Voile, linen-look and textured sheers', 'White, ivory and neutral tones', 'Wave and pinch pleat headings', 'Single or double tracks' ),
					'uses'      => array( 'Living and dining rooms', 'Villas with large glass walls', 'Offices and reception areas', 'Hotel rooms' ),
					'faqs'      => array( array( 'Are sheers private at night?', 'At night with lights on, sheers become more see-through. Layer them with blackout curtains or blinds for full night-time privacy.' ), array( 'Can sheers be washed?', 'Most sheer fabrics can be gently washed or dry-cleaned; we advise care per fabric.' ), array( 'Do you install on existing tracks?', 'Yes, if the track is in good condition. Otherwise we supply and fit a new one.' ) ),
				),
				'curtain-rods-tracks'          => array(
					'title'     => 'Curtain Rods & Tracks',
					'excerpt'   => 'Decorative rods, ceiling tracks and wave tracks supplied and installed so your curtains glide and hang perfectly.',
					'seo_title' => 'Curtain Rods & Tracks Dubai | Supply & Installation',
					'seo_desc'  => 'Curtain rods and tracks in Dubai: decorative rods, ceiling tracks, wave and bay-window tracks supplied and installed. Quote on WhatsApp.',
					'keyword'   => 'curtain tracks dubai',
					'intro'     => array( 'The right rod or track decides how your curtains hang, stack and move. We supply decorative rods, discreet ceiling tracks and wave systems for a modern, even fold.', 'Tracks can be bent for bay windows, recessed into gypsum ceilings or prepared for motorisation later.' ),
					'benefits'  => array( $b( 'Smooth glide', 'Quality runners that open and close effortlessly.' ), $b( 'Clean lines', 'Ceiling and recessed tracks for a minimal look.' ), $b( 'Bay windows', 'Tracks bent to follow curved and angled windows.' ), $b( 'Motor-ready', 'Options that can take a motor later.' ) ),
					'specs'     => array( 'Metal and wooden decorative rods', 'Ceiling, wall and recessed tracks', 'Wave, ripple-fold and pinch pleat systems', 'Single and double configurations' ),
					'uses'      => array( 'New apartments and villas', 'Replacing old or broken tracks', 'Gypsum ceiling pockets', 'Offices and hotels' ),
					'faqs'      => array( array( 'Rod or track — which is better?', 'Rods are decorative and suit classic styles; tracks are discreet and give a smoother, modern stack. We recommend based on your curtains and ceiling.' ), array( 'Can you install into gypsum ceilings?', 'Yes, with proper fixings or into a prepared curtain pocket.' ), array( 'Can a manual track be motorised later?', 'Some systems can. Tell us if you plan to motorise so we fit a compatible track.' ) ),
				),
				'motorized-curtains'           => array(
					'title'     => 'Motorized Curtains',
					'excerpt'   => 'Curtains that open and close at the touch of a button, a remote, a schedule or your voice assistant.',
					'seo_title' => 'Motorized Curtains Dubai | Smart & Remote Curtains',
					'seo_desc'  => 'Motorized curtains in Dubai: remote, app and smart-home control for villas, apartments and offices. Supply and installation. Quote on WhatsApp.',
					'keyword'   => 'motorized curtains dubai',
					'intro'     => array( 'Motorised tracks move heavy or tall curtains smoothly and quietly, and can be controlled by remote, wall switch, app or smart-home systems.', 'They are ideal for double-height windows, large glass walls and bedrooms where you want curtains to open with your morning alarm.' ),
					'benefits'  => array( $b( 'Convenience', 'Open every curtain in the room with one button.' ), $b( 'Hard-to-reach windows', 'Perfect for double-height and wide windows.' ), $b( 'Schedules', 'Automatic opening and closing to protect furniture from sun.' ), $b( 'Smart home', 'Integrates with common smart-home platforms (model dependent).' ) ),
					'specs'     => array( 'Wired and battery motor options', 'Remote, wall switch and app control', 'Quiet motors for bedrooms', 'Works with blackout and sheer curtains' ),
					'uses'      => array( 'Villas and penthouses', 'Home cinemas', 'Hotel suites', 'Boardrooms and offices' ),
					'faqs'      => array( array( 'Do motorised curtains need wiring?', 'Wired motors need a power point near the track; battery options avoid new wiring. We check this on site.' ), array( 'Can I still open them by hand?', 'Many systems allow manual pull during a power cut; we confirm per motor.' ), array( 'Will they work with Alexa or Google?', 'Many motors connect through a hub to popular smart-home assistants. Ask us for compatible models.' ) ),
				),
				'office-curtains'              => array(
					'title'     => 'Office Curtains',
					'excerpt'   => 'Professional curtains for offices, meeting rooms and receptions — glare control, privacy and a polished look.',
					'seo_title' => 'Office Curtains Dubai | Meeting Room & Office Curtains',
					'seo_desc'  => 'Office curtains in Dubai for meeting rooms, receptions and executive offices. Glare control, privacy and fire-rated options. Quote on WhatsApp.',
					'keyword'   => 'office curtains dubai',
					'intro'     => array( 'Offices need curtains that cut screen glare, add privacy to meeting rooms and look sharp for clients — while being durable and easy to maintain.', 'We work around office hours and fit-out programmes, and can offer fire-rated fabrics where building rules require them.' ),
					'benefits'  => array( $b( 'Glare control', 'Comfortable screens and presentations.' ), $b( 'Meeting privacy', 'Blackout or dim-out for boardrooms.' ), $b( 'Durable', 'Commercial-grade fabrics and tracks.' ), $b( 'Minimal disruption', 'Installation planned around your working hours.' ) ),
					'specs'     => array( 'Dim-out and blackout fabrics', 'Fire-rated fabric options', 'Ceiling tracks and motorised systems', 'Neutral corporate colours' ),
					'uses'      => array( 'Boardrooms and meeting rooms', 'Executive offices', 'Reception areas', 'Training rooms' ),
					'faqs'      => array( array( 'Do you supply fire-rated curtains?', 'Yes, fire-rated fabrics are available for projects where they are required; we provide the product details for approval.' ), array( 'Can you install after hours?', 'Yes, subject to building access, we can install evenings or weekends.' ), array( 'Curtains or blinds for an office?', 'Blinds suit desks and workstations; curtains add softness and acoustics in meeting rooms. Many offices combine both.' ) ),
				),
				'villa-curtain-installation'   => array(
					'title'     => 'Villa Curtain Installation',
					'excerpt'   => 'Complete curtain packages for villas — every room measured, styled, stitched and installed in one project.',
					'seo_title' => 'Villa Curtain Installation Dubai | Whole-Home Packages',
					'seo_desc'  => 'Villa curtain installation in Dubai: whole-home curtain packages with measurement, fabric selection, stitching and fitting. Quote on WhatsApp.',
					'keyword'   => 'villa curtains dubai',
					'intro'     => array( 'Villas have many window types — double-height living rooms, bay windows, large sliding doors and bedrooms that need blackout. We plan the whole house so every room works together.', 'One team measures, advises on fabrics and tracks, stitches and installs, so your villa is finished in a coordinated way.' ),
					'benefits'  => array( $b( 'Whole-home planning', 'Consistent style from majlis to bedrooms.' ), $b( 'One team', 'Measurement, stitching and installation in one place.' ), $b( 'Tall windows', 'Experience with double-height and wide openings.' ), $b( 'Mixed solutions', 'Curtains, blinds and motorisation where each fits best.' ) ),
					'specs'     => array( 'Blackout, sheer and decorative curtains', 'Tracks, rods and motorised systems', 'Majlis and formal-room styling', 'Coordinated blinds for wet areas and kitchens' ),
					'uses'      => array( 'New villa handovers', 'Villa renovations', 'Majlis and reception rooms', 'Holiday homes and rentals' ),
					'faqs'      => array( array( 'Do you visit the villa to measure?', 'Yes. We measure every window on site and bring fabric samples.' ), array( 'Can you work room by room?', 'Yes, we can phase the project to suit your budget and move-in date.' ), array( 'Do you remove old curtains?', 'We can remove old curtains and tracks as part of the job.' ) ),
				),
				'curtain-alteration-stitching' => array(
					'title'     => 'Curtain Alteration & Stitching',
					'excerpt'   => 'Shorten, lengthen, re-line or re-style your existing curtains — professional stitching and alterations.',
					'seo_title' => 'Curtain Alteration & Stitching Dubai | Tailoring Service',
					'seo_desc'  => 'Curtain alteration and stitching in Dubai: hemming, re-lining, new headings and repairs for existing curtains. Pickup options. Quote on WhatsApp.',
					'keyword'   => 'curtain stitching dubai',
					'intro'     => array( 'Moved house or changed tracks? We alter existing curtains so they fit their new windows — adjusting length and width, adding linings or changing the heading style.', 'We also stitch new curtains from fabric you already have.' ),
					'benefits'  => array( $b( 'Reuse what you have', 'Save on new fabric by altering existing curtains.' ), $b( 'Perfect length', 'Accurate hemming for a clean floor line.' ), $b( 'Add blackout', 'Add linings to existing curtains.' ), $b( 'New style', 'Change pleats, eyelets or wave headings.' ) ),
					'specs'     => array( 'Hemming and width adjustments', 'Blackout and thermal re-lining', 'Heading changes (pleat, eyelet, wave)', 'Stitching from customer fabric' ),
					'uses'      => array( 'After moving home', 'New tracks or rods', 'Worn linings', 'Custom fabric projects' ),
					'faqs'      => array( array( 'Can you stitch my own fabric?', 'Yes. Share the fabric details and window sizes and we will confirm quantities.' ), array( 'Do you collect the curtains?', 'Tell us your location on WhatsApp and we will arrange collection where possible.' ), array( 'How long do alterations take?', 'It depends on the work; we confirm the time when we see the curtains.' ) ),
				),
			),
		),
		'carpets'    => array(
			'title'     => 'Carpets',
			'excerpt'   => 'Wall-to-wall carpet, carpet tiles, runners and exhibition carpet — supplied, installed and maintained by Casa Vera Home.',
			'seo_title' => 'Carpets Dubai | Wall-to-Wall, Carpet Tiles & Runners',
			'seo_desc'  => 'Carpet supply and installation in Dubai & UAE: wall-to-wall, carpet tiles, exhibition carpet, runners and cleaning. Quote on WhatsApp.',
			'keyword'   => 'carpets dubai',
			'intro'     => 'Soft, quiet and warm underfoot — we supply and install carpet for homes, offices, hotels and events, and help keep it looking new.',
			'children'  => array(
				'wall-to-wall-carpet'          => array(
					'title'     => 'Wall to Wall Carpet',
					'excerpt'   => 'Seamless fitted carpet for bedrooms, majlis and offices — measured, stretched and installed edge to edge.',
					'seo_title' => 'Wall to Wall Carpet Dubai | Supply & Installation',
					'seo_desc'  => 'Wall to wall carpet in Dubai for bedrooms, majlis, hotels and offices. Wide range of colours and piles, professional fitting. Quote on WhatsApp.',
					'keyword'   => 'wall to wall carpet dubai',
					'intro'     => array( 'Wall-to-wall carpet covers the whole room in one continuous surface for a warm, quiet and luxurious feel.', 'We measure, plan seams, lay underlay and stretch or glue the carpet for a tight, long-lasting finish.' ),
					'benefits'  => array( $b( 'Warm & soft', 'Comfortable underfoot in bedrooms and majlis.' ), $b( 'Quieter rooms', 'Absorbs sound and reduces echo.' ), $b( 'Seamless look', 'Edge-to-edge coverage with planned seams.' ), $b( 'Wide choice', 'Cut pile, loop pile and patterned options.' ) ),
					'specs'     => array( 'Cut pile, loop pile and patterned carpet', 'Underlay for comfort and insulation', 'Stretch-in or glue-down installation', 'Residential and commercial grades' ),
					'uses'      => array( 'Bedrooms', 'Majlis and prayer rooms', 'Hotel rooms and corridors', 'Offices' ),
					'faqs'      => array( array( 'Do you remove the old carpet?', 'Yes, removal and disposal of old carpet can be included.' ), array( 'Is underlay necessary?', 'Underlay adds comfort, insulation and extends carpet life; we recommend it for most homes.' ), array( 'How long does fitting take?', 'Most rooms are fitted in a day once the carpet is ready.' ) ),
				),
				'carpet-tiles'                 => array(
					'title'     => 'Carpet Tiles',
					'excerpt'   => 'Modular carpet tiles for offices and commercial spaces — hard-wearing, easy to replace and quick to install.',
					'seo_title' => 'Carpet Tiles Dubai | Office Carpet Tiles Supply & Fit',
					'seo_desc'  => 'Carpet tiles in Dubai for offices, schools and commercial spaces. Durable, replaceable tiles in many patterns. Supply & installation. Quote on WhatsApp.',
					'keyword'   => 'carpet tiles dubai',
					'intro'     => array( 'Carpet tiles are the standard for offices: durable, acoustically soft and easy to lift for access to floor boxes and raised floors.', 'Worn or stained tiles can be swapped individually, keeping the floor fresh for years.' ),
					'benefits'  => array( $b( 'Replace single tiles', 'Swap damaged tiles instead of the whole floor.' ), $b( 'Raised-floor friendly', 'Easy access to cables and floor boxes.' ), $b( 'Design freedom', 'Mix colours and patterns to zone spaces.' ), $b( 'Hard-wearing', 'Commercial grades for heavy traffic.' ) ),
					'specs'     => array( 'Commercial loop and cut-pile tiles', 'Common size 50 × 50 cm', 'Quarter-turn, ashlar and brick lay patterns', 'Tackifier or glue-down installation' ),
					'uses'      => array( 'Offices and co-working spaces', 'Schools and training rooms', 'Retail and showrooms', 'Raised access floors' ),
					'faqs'      => array( array( 'Can carpet tiles go on raised floors?', 'Yes, they are the usual choice for raised access floors.' ), array( 'Can you work outside office hours?', 'Yes, we can phase installation around your operations.' ), array( 'Do you keep spare tiles?', 'We recommend keeping a small stock of spares for future replacements.' ) ),
				),
				'exhibition-carpet'            => array(
					'title'     => 'Exhibition Carpet',
					'excerpt'   => 'Fast-install carpet for exhibitions, events and stands — in bold colours and ready on tight deadlines.',
					'seo_title' => 'Exhibition Carpet Dubai | Event & Stand Carpet',
					'seo_desc'  => 'Exhibition carpet in Dubai for stands, events and weddings. Many colours, quick supply and fast installation for tight event schedules. WhatsApp us.',
					'keyword'   => 'exhibition carpet dubai',
					'intro'     => array( 'Events run on tight timelines. Exhibition carpet is supplied in large rolls and a wide range of colours, and laid quickly for stands, halls and outdoor events.', 'We coordinate delivery and installation windows with organisers and stand builders.' ),
					'benefits'  => array( $b( 'Fast installation', 'Laid quickly within build-up windows.' ), $b( 'Bold colours', 'Match your brand or event theme.' ), $b( 'Budget-friendly', 'Economical for short-term use.' ), $b( 'Event-ready', 'Coordinated with organisers and stand builders.' ) ),
					'specs'     => array( 'Needle-punch exhibition carpet', 'Wide colour range', 'Roll widths for large halls', 'Protective film on request' ),
					'uses'      => array( 'Exhibition stands', 'Conferences and launches', 'Weddings and gala events', 'Temporary retail pop-ups' ),
					'faqs'      => array( array( 'How quickly can you supply?', 'Tell us the event date and area on WhatsApp; stocked colours can often be arranged at short notice.' ), array( 'Do you remove the carpet after the event?', 'Removal can be included in the quote.' ), array( 'Can you match my brand colour?', 'We offer many colours and will suggest the closest match.' ) ),
				),
				'office-carpet-installation'   => array(
					'title'     => 'Office Carpet Installation',
					'excerpt'   => 'Office carpet supply and installation planned around your working hours and fit-out programme.',
					'seo_title' => 'Office Carpet Installation Dubai | Commercial Fitting',
					'seo_desc'  => 'Office carpet installation in Dubai: carpet tiles and broadloom for offices, fitted out of hours with minimal disruption. Quote on WhatsApp.',
					'keyword'   => 'office carpet installation dubai',
					'intro'     => array( 'A new office floor should go in without stopping your business. We plan installation zone by zone or out of hours, move furniture where agreed and leave the office ready to use.', 'We work with fit-out contractors and facility managers on programme and approvals.' ),
					'benefits'  => array( $b( 'Minimal downtime', 'Night and weekend installation available.' ), $b( 'Zoned planning', 'Phased work so teams keep working.' ), $b( 'Fit-out ready', 'Documents and samples for approvals.' ), $b( 'Clean handover', 'Old carpet removed and site left tidy.' ) ),
					'specs'     => array( 'Carpet tiles and broadloom', 'Floor preparation and levelling', 'Old carpet removal and disposal', 'Furniture moving on request' ),
					'uses'      => array( 'Corporate offices', 'Co-working spaces', 'Government and education buildings', 'Hotels and back offices' ),
					'faqs'      => array( array( 'Can you install at night?', 'Yes, subject to building access rules.' ), array( 'Do you move furniture?', 'We can move furniture as part of the job when agreed in advance.' ), array( 'Do you provide samples for approval?', 'Yes, samples and product data are available for consultants and managers.' ) ),
				),
				'carpet-cleaning-maintenance'  => array(
					'title'     => 'Carpet Cleaning & Maintenance',
					'excerpt'   => 'Deep cleaning, stain treatment and repairs that keep home and office carpets fresh for longer.',
					'seo_title' => 'Carpet Cleaning & Maintenance Dubai | Deep Clean & Repair',
					'seo_desc'  => 'Carpet cleaning and maintenance in Dubai: deep cleaning, stain treatment and repairs for homes and offices. Book on WhatsApp.',
					'keyword'   => 'carpet cleaning dubai',
					'intro'     => array( 'Dust and sand are part of life in the UAE, and they wear carpet fibres quickly. Regular deep cleaning removes embedded dirt and refreshes colour.', 'We also repair seams, patch damaged areas and replace worn carpet tiles.' ),
					'benefits'  => array( $b( 'Fresher rooms', 'Removes embedded dust and odours.' ), $b( 'Longer life', 'Protects fibres from grit wear.' ), $b( 'Stain treatment', 'Targeted treatment for common stains.' ), $b( 'Repairs', 'Seams, patches and tile replacement.' ) ),
					'specs'     => array( 'Deep cleaning for residential and commercial carpet', 'Spot and stain treatment', 'Seam and patch repairs', 'Scheduled maintenance plans for offices' ),
					'uses'      => array( 'Homes and villas', 'Offices', 'Hotels and serviced apartments', 'Majlis and prayer rooms' ),
					'faqs'      => array( array( 'How often should carpet be cleaned?', 'Homes typically every 6–12 months; busy offices more often. We suggest a plan based on traffic.' ), array( 'How long does it take to dry?', 'Drying time depends on the method and ventilation; we advise on the day.' ), array( 'Can all stains be removed?', 'Many stains can be removed or reduced; some permanent stains may need a patch repair.' ) ),
				),
				'custom-carpet-runners'        => array(
					'title'     => 'Custom Carpet Runners',
					'excerpt'   => 'Made-to-measure runners for stairs, corridors and hallways — cut, bound and fitted to your space.',
					'seo_title' => 'Custom Carpet Runners Dubai | Stair & Hallway Runners',
					'seo_desc'  => 'Custom carpet runners in Dubai for stairs, corridors and hallways. Made to measure, bound edges, professional fitting. Quote on WhatsApp.',
					'keyword'   => 'carpet runners dubai',
					'intro'     => array( 'A runner protects stairs and corridors, softens footsteps and adds a designer touch to hallways.', 'We cut runners to your exact length and width, bind the edges and fit them securely on stairs with rods or grippers.' ),
					'benefits'  => array( $b( 'Exact fit', 'Made to your stair and corridor sizes.' ), $b( 'Safer stairs', 'Better grip and softer steps.' ), $b( 'Quieter', 'Reduces footstep noise in villas.' ), $b( 'Designer finish', 'Bound or taped edges in matching colours.' ) ),
					'specs'     => array( 'Stair, corridor and hallway runners', 'Bound or taped edges', 'Stair rods and gripper fitting', 'Plain, patterned and striped designs' ),
					'uses'      => array( 'Villa staircases', 'Hotel corridors', 'Entrance halls', 'Offices and lobbies' ),
					'faqs'      => array( array( 'Can a runner fit curved stairs?', 'Yes, we measure and fit runners to curved and winding stairs.' ), array( 'Do runners damage marble stairs?', 'Fitting methods are chosen to protect your stairs; we discuss options on site.' ), array( 'Can I choose the edge colour?', 'Yes, edge binding colours can be selected to match.' ) ),
				),
			),
		),
		'wallpaper'  => array(
			'title'     => 'Wallpaper',
			'excerpt'   => '3D, textured and custom mural wallpaper for homes, kids rooms, offices and hotels — supplied and installed by Casa Vera Home.',
			'seo_title' => 'Wallpaper Dubai | 3D, Textured & Custom Murals',
			'seo_desc'  => 'Wallpaper supply and installation in Dubai & UAE: 3D, textured, kids room, office wallpaper and custom murals. Removal service too. Quote on WhatsApp.',
			'keyword'   => 'wallpaper dubai',
			'intro'     => 'Transform a wall in a day — from subtle textures to bold 3D designs and custom murals printed to your size.',
			'children'  => array(
				'3d-wallpaper'                      => array(
					'title'     => '3D Wallpaper',
					'excerpt'   => 'Wallpaper with depth and dimension — stone, geometric and abstract effects that make a feature wall stand out.',
					'seo_title' => '3D Wallpaper Dubai | Feature Walls Supply & Installation',
					'seo_desc'  => '3D wallpaper in Dubai for feature walls in living rooms, bedrooms and offices. Stone, geometric and abstract designs installed. Quote on WhatsApp.',
					'keyword'   => '3d wallpaper dubai',
					'intro'     => array( '3D wallpaper uses printed or embossed designs to create an illusion of depth — stone, brick, geometric panels or abstract art — without the cost of real cladding.', 'It is ideal for a single statement wall behind a TV, bed or reception desk.' ),
					'benefits'  => array( $b( 'Statement walls', 'Instant focal point for any room.' ), $b( 'Cost-effective', 'The look of cladding at a fraction of the cost.' ), $b( 'Fast install', 'Most feature walls done in a day.' ), $b( 'Many designs', 'Stone, geometric, floral and abstract.' ) ),
					'specs'     => array( 'Printed and embossed 3D designs', 'Vinyl and non-woven backings', 'Wipeable finishes available', 'Wall preparation included' ),
					'uses'      => array( 'TV and living room walls', 'Bedroom headboard walls', 'Reception and retail walls', 'Restaurants and cafés' ),
					'faqs'      => array( array( 'Is 3D wallpaper actually raised?', 'Some designs are embossed with real texture; others are printed to look 3D. We show both on samples.' ), array( 'Can it go in bathrooms?', 'Only suitable vinyl types in well-ventilated areas; we advise per room.' ), array( 'Does the wall need preparation?', 'Walls should be smooth and dry; we prepare and prime as needed.' ) ),
				),
				'textured-wallpaper'                => array(
					'title'     => 'Textured Wallpaper',
					'excerpt'   => 'Linen, grasscloth-look and plaster textures that add warmth and luxury to walls.',
					'seo_title' => 'Textured Wallpaper Dubai | Linen & Grasscloth Looks',
					'seo_desc'  => 'Textured wallpaper in Dubai: linen, grasscloth-look and plaster-effect wallcoverings for homes, hotels and offices. Supply & install. WhatsApp us.',
					'keyword'   => 'textured wallpaper dubai',
					'intro'     => array( 'Textured wallpapers bring a tactile, layered look — soft linen weaves, natural grasscloth effects and subtle plaster finishes.', 'They hide minor wall imperfections and suit calm, luxurious interiors.' ),
					'benefits'  => array( $b( 'Luxury feel', 'Rich textures for refined interiors.' ), $b( 'Hides imperfections', 'Texture masks small wall flaws.' ), $b( 'Neutral palettes', 'Easy to style with any furniture.' ), $b( 'Durable', 'Commercial-grade options for hotels and offices.' ) ),
					'specs'     => array( 'Linen, silk and grasscloth-look finishes', 'Plaster and concrete effects', 'Vinyl and non-woven types', 'Residential and commercial grades' ),
					'uses'      => array( 'Living and dining rooms', 'Bedrooms', 'Hotel rooms and corridors', 'Executive offices' ),
					'faqs'      => array( array( 'Is textured wallpaper washable?', 'Vinyl textures are wipeable; natural-look papers need gentle care. We advise per product.' ), array( 'Can you cover a whole villa?', 'Yes, we measure every room and plan pattern matching.' ), array( 'Do you show samples at home?', 'Yes, we bring sample books to your site.' ) ),
				),
				'kids-room-wallpaper'               => array(
					'title'     => 'Kids Room Wallpaper',
					'excerpt'   => 'Playful, wipeable wallpaper and murals for nurseries and kids rooms.',
					'seo_title' => 'Kids Room Wallpaper Dubai | Nursery & Kids Murals',
					'seo_desc'  => 'Kids room wallpaper in Dubai: nursery designs, playful patterns and custom murals with wipeable finishes. Supply & installation. Quote on WhatsApp.',
					'keyword'   => 'kids room wallpaper dubai',
					'intro'     => array( 'Kids rooms deserve walls that spark imagination — from soft nursery patterns to jungles, space scenes and custom murals with your child’s name.', 'We recommend wipeable finishes that survive crayons and little hands.' ),
					'benefits'  => array( $b( 'Playful designs', 'Themes children love.' ), $b( 'Wipeable', 'Easy-clean finishes for busy rooms.' ), $b( 'Personalised', 'Custom murals and names.' ), $b( 'Quick makeover', 'A new room in a day.' ) ),
					'specs'     => array( 'Nursery and kids patterns', 'Custom printed murals', 'Wipeable vinyl finishes', 'Feature wall or full room' ),
					'uses'      => array( 'Nurseries', 'Kids bedrooms', 'Playrooms', 'Nurseries and schools' ),
					'faqs'      => array( array( 'Is kids wallpaper safe?', 'We use quality wallcoverings from established suppliers; ask us for product details.' ), array( 'Can we personalise a mural?', 'Yes, murals can include names and custom artwork.' ), array( 'Can it be removed when kids grow up?', 'Many non-woven papers remove cleanly; we also offer a removal service.' ) ),
				),
				'office-wallpaper'                  => array(
					'title'     => 'Office Wallpaper',
					'excerpt'   => 'Branded walls, meeting room textures and durable commercial wallcoverings for offices.',
					'seo_title' => 'Office Wallpaper Dubai | Commercial & Branded Walls',
					'seo_desc'  => 'Office wallpaper in Dubai: branded walls, meeting room textures and durable commercial wallcoverings, installed out of hours. Quote on WhatsApp.',
					'keyword'   => 'office wallpaper dubai',
					'intro'     => array( 'Wallpaper is one of the fastest ways to bring your brand and culture into an office — from logo walls in reception to calm textures in meeting rooms.', 'Commercial-grade vinyl wallcoverings are durable and easy to clean in busy spaces.' ),
					'benefits'  => array( $b( 'Brand walls', 'Print logos, values and imagery.' ), $b( 'Durable', 'Commercial vinyl for high-traffic areas.' ), $b( 'Acoustic comfort', 'Textured options soften sound.' ), $b( 'Out-of-hours install', 'No disruption to your team.' ) ),
					'specs'     => array( 'Custom printed brand walls', 'Commercial vinyl wallcoverings', 'Textured meeting-room finishes', 'Fire-rated options on request' ),
					'uses'      => array( 'Reception areas', 'Meeting rooms', 'Open-plan offices', 'Corridors and breakout areas' ),
					'faqs'      => array( array( 'Can you print our logo on wallpaper?', 'Yes, custom prints are made to your wall size and artwork.' ), array( 'Do you install after hours?', 'Yes, subject to building access.' ), array( 'Is commercial wallpaper washable?', 'Commercial vinyl is wipeable and designed for heavy use.' ) ),
				),
				'custom-wall-murals'                => array(
					'title'     => 'Custom Wall Murals',
					'excerpt'   => 'Any image, artwork or photo printed to fit your wall exactly — for homes, cafés, offices and retail.',
					'seo_title' => 'Custom Wall Murals Dubai | Printed Wallpaper Murals',
					'seo_desc'  => 'Custom wall murals in Dubai: your artwork or photo printed to size and installed for homes, cafés, offices and shops. Quote on WhatsApp.',
					'keyword'   => 'custom wall murals dubai',
					'intro'     => array( 'A custom mural turns any wall into a canvas: skylines, landscapes, artwork, brand imagery or your own photographs, printed to your exact wall size.', 'We check image resolution, plan panel joins and install for a seamless result.' ),
					'benefits'  => array( $b( 'Truly unique', 'Your image, your size.' ), $b( 'Seamless joins', 'Panels aligned carefully on site.' ), $b( 'Any space', 'Homes, cafés, retail and offices.' ), $b( 'Quick change', 'Transform a space in a day.' ) ),
					'specs'     => array( 'Printed to exact wall dimensions', 'Matt, satin and textured finishes', 'Image resolution check and proof', 'Professional installation' ),
					'uses'      => array( 'Living room feature walls', 'Cafés and restaurants', 'Retail and showrooms', 'Offices and receptions' ),
					'faqs'      => array( array( 'What image quality do you need?', 'High-resolution images work best; we check your file and advise before printing.' ), array( 'Can you help find artwork?', 'Yes, we can suggest designs and stock imagery options.' ), array( 'Will I see a proof first?', 'Yes, we share a proof for approval before printing.' ) ),
				),
				'wallpaper-removal'                 => array(
					'title'     => 'Wallpaper Removal',
					'excerpt'   => 'Clean removal of old wallpaper and wall preparation, ready for paint or new wallpaper.',
					'seo_title' => 'Wallpaper Removal Dubai | Wall Prep for Paint or Paper',
					'seo_desc'  => 'Wallpaper removal in Dubai: careful stripping of old wallpaper and wall preparation ready for paint or new wallcovering. Quote on WhatsApp.',
					'keyword'   => 'wallpaper removal dubai',
					'intro'     => array( 'Removing old wallpaper badly can damage plaster and gypsum. We strip carefully, remove adhesive residue and prepare walls so the next finish looks perfect.', 'Ideal before a repaint, a new wallpaper or when handing back a rental.' ),
					'benefits'  => array( $b( 'Careful stripping', 'Protects plaster and gypsum boards.' ), $b( 'Clean walls', 'Adhesive residue removed.' ), $b( 'Ready to finish', 'Walls prepared for paint or new paper.' ), $b( 'Tidy site', 'Waste removed and room left clean.' ) ),
					'specs'     => array( 'Removal of vinyl, paper and non-woven types', 'Adhesive residue removal', 'Minor wall repairs and skim', 'Priming for new finish' ),
					'uses'      => array( 'Before repainting', 'Before new wallpaper', 'Rental handovers', 'Office refurbishments' ),
					'faqs'      => array( array( 'Will removal damage my walls?', 'We use careful methods to minimise damage and repair minor marks as part of preparation.' ), array( 'Can you install new wallpaper right after?', 'Yes, we can remove and install in one project.' ), array( 'How long does it take?', 'Most rooms are stripped and prepared in a day or two.' ) ),
				),
				'commercial-wallpaper-installation' => array(
					'title'     => 'Commercial Wallpaper Installation',
					'excerpt'   => 'Large-scale wallcovering installation for hotels, offices, retail and healthcare projects.',
					'seo_title' => 'Commercial Wallpaper Installation Dubai | Hotels & Offices',
					'seo_desc'  => 'Commercial wallpaper installation in Dubai for hotels, offices, retail and healthcare. Programme-driven teams and approval documents. WhatsApp us.',
					'keyword'   => 'commercial wallpaper installation dubai',
					'intro'     => array( 'Commercial projects need consistent quality across hundreds of walls, delivered to the fit-out programme. Our teams install commercial wallcoverings in hotels, offices, retail and clinics.', 'We provide samples and product data for approvals and coordinate with main contractors.' ),
					'benefits'  => array( $b( 'Programme-driven', 'Crews scaled to your schedule.' ), $b( 'Consistent finish', 'Same quality floor to floor.' ), $b( 'Approvals support', 'Samples and data sheets for consultants.' ), $b( 'Commercial grades', 'Durable, cleanable wallcoverings.' ) ),
					'specs'     => array( 'Type II commercial vinyl wallcoverings', 'Fire-rated options on request', 'Large-format and custom prints', 'Wall preparation and priming' ),
					'uses'      => array( 'Hotels and serviced apartments', 'Corporate offices', 'Retail and malls', 'Clinics and schools' ),
					'faqs'      => array( array( 'Do you work with main contractors?', 'Yes, we regularly coordinate with fit-out and main contractors.' ), array( 'Can you provide mock-ups?', 'Sample panels can be arranged for approval on larger projects.' ), array( 'Do you work at night?', 'Yes, where the site allows.' ) ),
				),
			),
		),
		'blinds'     => array(
			'title'     => 'Blinds',
			'excerpt'   => 'Roller, Roman, Venetian, vertical, blackout and motorised blinds — measured and installed across Dubai by Casa Vera Home.',
			'seo_title' => 'Blinds Dubai | Roller, Roman, Venetian & Motorised',
			'seo_desc'  => 'Blinds in Dubai & UAE: roller, Roman, Venetian, vertical, blackout and motorised blinds for homes and offices. Free measurement. Quote on WhatsApp.',
			'keyword'   => 'blinds dubai',
			'intro'     => 'Neat, practical light control for every window — from simple roller blinds to motorised systems for whole offices.',
			'children'  => array(
				'roller-blinds'   => array(
					'title'     => 'Roller Blinds',
					'excerpt'   => 'Clean, simple roller blinds in sunscreen, dim-out and blackout fabrics.',
					'seo_title' => 'Roller Blinds Dubai | Sunscreen & Blackout Rollers',
					'seo_desc'  => 'Roller blinds in Dubai: sunscreen, dim-out and blackout fabrics made to measure for homes and offices. Installation included. Quote on WhatsApp.',
					'keyword'   => 'roller blinds dubai',
					'intro'     => array( 'Roller blinds are the most popular window solution in the UAE: slim, modern and available in fabrics that cut glare, dim light or block it completely.', 'Sunscreen fabrics keep your view while reducing heat and glare.' ),
					'benefits'  => array( $b( 'Minimal look', 'Slim profile that suits modern interiors.' ), $b( 'Heat & glare', 'Sunscreen fabrics reduce solar heat.' ), $b( 'Blackout option', 'Full darkness for bedrooms.' ), $b( 'Easy to clean', 'Wipeable fabrics available.' ) ),
					'specs'     => array( 'Sunscreen (various openness), dim-out and blackout', 'Chain, spring and motorised operation', 'Inside or outside recess fitting', 'Cassette and open-roll options' ),
					'uses'      => array( 'Living rooms and bedrooms', 'Kitchens', 'Offices', 'Schools and clinics' ),
					'faqs'      => array( array( 'Will sunscreen blinds block the view?', 'No — sunscreen fabrics let you see out while reducing glare and heat.' ), array( 'Can I have day and night in one?', 'Yes, a double roller combines sunscreen and blackout.' ), array( 'Can they be motorised?', 'Yes, roller blinds are easy to motorise.' ) ),
				),
				'venetian-blinds' => array(
					'title'     => 'Venetian Blinds',
					'excerpt'   => 'Aluminium and wood-look slatted blinds with precise tilt control of light and privacy.',
					'seo_title' => 'Venetian Blinds Dubai | Aluminium & Wood Venetians',
					'seo_desc'  => 'Venetian blinds in Dubai: aluminium and wood-look slats with adjustable tilt for light and privacy. Made to measure and installed. WhatsApp us.',
					'keyword'   => 'venetian blinds dubai',
					'intro'     => array( 'Venetian blinds let you tilt slats to fine-tune light and privacy through the day, then raise them fully to open the window.', 'Aluminium slats are practical for kitchens and bathrooms; wood-look slats add warmth to living spaces.' ),
					'benefits'  => array( $b( 'Precise control', 'Tilt for the exact light you want.' ), $b( 'Moisture-friendly', 'Aluminium suits kitchens and bathrooms.' ), $b( 'Warm finishes', 'Wood-look slats for living areas.' ), $b( 'Durable', 'Long-lasting slats and mechanisms.' ) ),
					'specs'     => array( 'Aluminium and wood-look slats', 'Several slat widths', 'Cord or wand tilt control', 'Inside or outside recess fitting' ),
					'uses'      => array( 'Kitchens and bathrooms', 'Home offices', 'Commercial offices', 'Villas and apartments' ),
					'faqs'      => array( array( 'Are Venetian blinds hard to clean?', 'A quick dust or wipe keeps them clean; aluminium is the easiest.' ), array( 'Can they go in bathrooms?', 'Aluminium Venetians are a good choice for humid areas.' ), array( 'Do you offer wood slats?', 'We offer wood-look options suited to the UAE climate.' ) ),
				),
				'vertical-blinds' => array(
					'title'     => 'Vertical Blinds',
					'excerpt'   => 'Practical vertical blinds for wide windows and sliding doors in homes and offices.',
					'seo_title' => 'Vertical Blinds Dubai | Office & Sliding Door Blinds',
					'seo_desc'  => 'Vertical blinds in Dubai for wide windows, sliding doors and offices. Durable fabrics and PVC slats, made to measure. Quote on WhatsApp.',
					'keyword'   => 'vertical blinds dubai',
					'intro'     => array( 'Vertical blinds are a practical, economical choice for wide windows and sliding doors, stacking neatly to one side.', 'Slats rotate to control light and privacy and are easy to replace individually.' ),
					'benefits'  => array( $b( 'Wide windows', 'Covers large openings cost-effectively.' ), $b( 'Sliding doors', 'Stacks to the side for easy access.' ), $b( 'Replaceable slats', 'Swap a damaged slat, not the whole blind.' ), $b( 'Budget-friendly', 'Great value for offices.' ) ),
					'specs'     => array( 'Fabric and PVC slats', 'Dim-out and blackout fabrics', 'Left, right or centre stack', 'Wand or cord control' ),
					'uses'      => array( 'Offices and schools', 'Sliding balcony doors', 'Wide living room windows', 'Warehouses and showrooms' ),
					'faqs'      => array( array( 'Are vertical blinds outdated?', 'Modern fabrics and colours make them a neat, practical option, especially for offices and sliding doors.' ), array( 'Can individual slats be replaced?', 'Yes, slats can be replaced individually.' ), array( 'Do they block light fully?', 'Blackout slats reduce light significantly; small gaps remain at edges.' ) ),
				),
				'blackout-blinds' => array(
					'title'     => 'Blackout Blinds',
					'excerpt'   => 'Blinds that block light for sleep, media rooms and presentations — with side channels for maximum darkness.',
					'seo_title' => 'Blackout Blinds Dubai | Bedroom & Media Room Blinds',
					'seo_desc'  => 'Blackout blinds in Dubai for bedrooms, nurseries, media rooms and meeting rooms. Roller and Roman styles, side channels available. WhatsApp us.',
					'keyword'   => 'blackout blinds dubai',
					'intro'     => array( 'Blackout blinds use opaque fabrics to stop light passing through — essential for bedrooms, nurseries and media rooms in sunny Dubai.', 'For the darkest result, cassettes and side channels close the light gaps around the edges.' ),
					'benefits'  => array( $b( 'Better sleep', 'Dark rooms at any time of day.' ), $b( 'Cooler rooms', 'Blocks heat along with light.' ), $b( 'Presentations', 'Perfect for meeting and media rooms.' ), $b( 'Neat fit', 'Slim inside-recess installation.' ) ),
					'specs'     => array( 'Roller and Roman blackout blinds', 'Cassette and side-channel systems', 'Motorised options', 'Wide colour range' ),
					'uses'      => array( 'Bedrooms and nurseries', 'Home cinemas', 'Meeting rooms', 'Hotel rooms' ),
					'faqs'      => array( array( 'Blackout blinds or curtains?', 'Blinds are neater and space-saving; curtains are softer and can overlap walls for less light leakage. Many clients combine both.' ), array( 'How dark can it get?', 'With side channels, rooms can be made very dark.' ), array( 'Can blackout blinds be motorised?', 'Yes.' ) ),
				),
				'roman-blinds'    => array(
					'title'     => 'Roman Blinds',
					'excerpt'   => 'Soft fabric blinds that fold into elegant pleats — the warmth of curtains with the neatness of a blind.',
					'seo_title' => 'Roman Blinds Dubai | Made-to-Measure Fabric Blinds',
					'seo_desc'  => 'Roman blinds in Dubai: made-to-measure fabric blinds with elegant folds, lined or blackout. Supply and installation. Quote on WhatsApp.',
					'keyword'   => 'roman blinds dubai',
					'intro'     => array( 'Roman blinds are made from curtain-style fabric that folds neatly when raised, bringing softness and colour to a window without the bulk of curtains.', 'They can be lined, thermal-lined or blackout.' ),
					'benefits'  => array( $b( 'Soft & elegant', 'The look of fabric with a tidy finish.' ), $b( 'Space-saving', 'Great where curtains won’t fit.' ), $b( 'Lined options', 'Privacy, thermal or blackout linings.' ), $b( 'Coordinated', 'Match your curtains and cushions.' ) ),
					'specs'     => array( 'Wide range of decorative fabrics', 'Standard, thermal and blackout linings', 'Cord, chain or motorised operation', 'Inside or outside recess' ),
					'uses'      => array( 'Bedrooms and nurseries', 'Kitchen and dining windows', 'Home offices', 'Hotel suites' ),
					'faqs'      => array( array( 'Can Roman blinds be blackout?', 'Yes, with a blackout lining.' ), array( 'Can you use my fabric?', 'Often yes; we check the fabric is suitable for folding.' ), array( 'Are they good for kitchens?', 'Yes, away from direct splash zones.' ) ),
				),
				'motorized-blinds' => array(
					'title'     => 'Motorized Blinds',
					'excerpt'   => 'Smart blinds controlled by remote, app, schedule or voice — ideal for high and hard-to-reach windows.',
					'seo_title' => 'Motorized Blinds Dubai | Smart & Remote Blinds',
					'seo_desc'  => 'Motorized blinds in Dubai: roller, Roman and blackout blinds with remote, app and smart-home control. Supply and installation. WhatsApp us.',
					'keyword'   => 'motorized blinds dubai',
					'intro'     => array( 'Motorised blinds raise and lower at the touch of a button — perfect for tall windows, skylights and rooms with many windows.', 'Schedule them to protect furniture from sun or link them to your smart-home system.' ),
					'benefits'  => array( $b( 'One-touch control', 'Operate groups of blinds together.' ), $b( 'Tall windows', 'No more reaching or tangled cords.' ), $b( 'Child-safe', 'No loose cords.' ), $b( 'Smart schedules', 'Automate with timers and sensors.' ) ),
					'specs'     => array( 'Battery and wired motors', 'Remote, wall switch and app control', 'Roller, Roman and blackout options', 'Smart-home integration (model dependent)' ),
					'uses'      => array( 'Villas and penthouses', 'Offices and boardrooms', 'Skylights and high windows', 'Hotels' ),
					'faqs'      => array( array( 'Do I need an electrician?', 'Battery motors avoid new wiring; wired motors need a power point. We check on site.' ), array( 'How long do batteries last?', 'Battery life depends on use; many models recharge easily.' ), array( 'Can existing blinds be motorised?', 'Sometimes; we assess your current blinds first.' ) ),
				),
				'office-blinds'   => array(
					'title'     => 'Office Blinds',
					'excerpt'   => 'Glare-free workspaces with roller, vertical and motorised blinds for offices of every size.',
					'seo_title' => 'Office Blinds Dubai | Roller, Vertical & Motorised',
					'seo_desc'  => 'Office blinds in Dubai: glare control with roller, vertical and motorised blinds, installed out of hours for minimal disruption. Quote on WhatsApp.',
					'keyword'   => 'office blinds dubai',
					'intro'     => array( 'The right office blinds reduce screen glare and heat gain, keep a consistent look across the façade and give privacy to meeting rooms.', 'We survey, recommend fabrics and install floor by floor around your operations.' ),
					'benefits'  => array( $b( 'Glare control', 'Comfortable screens all day.' ), $b( 'Energy savings', 'Reduce solar heat gain.' ), $b( 'Uniform façade', 'Consistent look floor to floor.' ), $b( 'Low disruption', 'Out-of-hours installation.' ) ),
					'specs'     => array( 'Sunscreen roller blinds', 'Vertical and Venetian options', 'Motorised group control', 'Fire-rated fabrics on request' ),
					'uses'      => array( 'Open-plan offices', 'Meeting rooms', 'Receptions', 'Schools and clinics' ),
					'faqs'      => array( array( 'Which blind is best for offices?', 'Sunscreen roller blinds are the most common for glare control; blackout for meeting rooms.' ), array( 'Do you install out of hours?', 'Yes, subject to building access.' ), array( 'Can blinds be grouped on one control?', 'Yes, motorised blinds can be grouped by zone.' ) ),
				),
			),
		),
		'upholstery' => array(
			'title'     => 'Upholstery',
			'excerpt'   => 'Sofa, chair, restaurant, car and outdoor upholstery — re-covering and repairs by Casa Vera Home craftsmen.',
			'seo_title' => 'Upholstery Dubai | Sofa, Chair, Restaurant & Car',
			'seo_desc'  => 'Upholstery services in Dubai & UAE: sofa and chair re-upholstery, restaurant seating, car seats, outdoor furniture and cushions. Quote on WhatsApp.',
			'keyword'   => 'upholstery dubai',
			'intro'     => 'Give well-loved furniture a second life — new fabric, new foam and expert repairs for homes, restaurants and vehicles.',
			'children'  => array(
				'sofa-upholstery'               => array(
					'title'     => 'Sofa Upholstery',
					'excerpt'   => 'Re-cover, re-foam and repair sofas — keep the frame you love with a fresh new look.',
					'seo_title' => 'Sofa Upholstery Dubai | Re-cover, Re-foam & Repair',
					'seo_desc'  => 'Sofa upholstery in Dubai: re-covering, new foam and repairs for sofas and couches in fabric or leather-look. Pickup available. Quote on WhatsApp.',
					'keyword'   => 'sofa upholstery dubai',
					'intro'     => array( 'A good sofa frame can last decades. Re-upholstery replaces tired fabric and sagging cushions so your sofa looks and feels new.', 'Choose from a wide range of fabrics and finishes, with new foam for comfort.' ),
					'benefits'  => array( $b( 'Save money', 'Often less than buying a quality new sofa.' ), $b( 'New comfort', 'Fresh foam and cushion filling.' ), $b( 'Your style', 'Choose any fabric and colour.' ), $b( 'Sustainable', 'Keep good furniture out of landfill.' ) ),
					'specs'     => array( 'Fabric and leather-look materials', 'Foam and cushion replacement', 'Frame and spring repairs', 'Pickup and delivery options' ),
					'uses'      => array( 'Living room sofas', 'Majlis seating', 'Corner and L-shaped sofas', 'Office lounges' ),
					'faqs'      => array( array( 'How long does sofa upholstery take?', 'Timing depends on size and fabric availability; we confirm when quoting.' ), array( 'Do you collect the sofa?', 'Pickup and delivery can be arranged.' ), array( 'Can you repair a broken frame?', 'Many frame and spring issues can be repaired during re-upholstery.' ) ),
				),
				'chair-upholstery'              => array(
					'title'     => 'Chair Upholstery',
					'excerpt'   => 'Dining chairs, armchairs and office chairs re-covered and repaired.',
					'seo_title' => 'Chair Upholstery Dubai | Dining, Arm & Office Chairs',
					'seo_desc'  => 'Chair upholstery in Dubai: dining chairs, armchairs and office chairs re-covered with new foam and fabric. Quote on WhatsApp.',
					'keyword'   => 'chair upholstery dubai',
					'intro'     => array( 'Worn seat pads and faded fabrics make a whole room look tired. We re-cover dining chairs, armchairs and office chairs with durable new fabric and foam.', 'Sets are finished consistently so every chair matches.' ),
					'benefits'  => array( $b( 'Matching sets', 'Consistent finish across all chairs.' ), $b( 'Durable fabrics', 'Stain-resistant options for dining.' ), $b( 'New foam', 'Comfortable seating again.' ), $b( 'Quick turnaround', 'Dining sets done efficiently.' ) ),
					'specs'     => array( 'Dining, accent and office chairs', 'Stain-resistant and easy-clean fabrics', 'Foam and webbing replacement', 'Decorative nailhead finishing' ),
					'uses'      => array( 'Dining rooms', 'Living rooms', 'Offices', 'Hotels and cafés' ),
					'faqs'      => array( array( 'Can you match my existing fabric?', 'We try to match; otherwise we suggest close alternatives.' ), array( 'Is it worth re-upholstering office chairs?', 'For quality chairs, yes — it restores comfort at lower cost than new.' ), array( 'Do you do leather-look?', 'Yes, leather-look materials are available.' ) ),
				),
				'restaurant-seating-upholstery' => array(
					'title'     => 'Restaurant Seating Upholstery',
					'excerpt'   => 'Banquettes, booths and chairs re-upholstered in commercial-grade materials with minimal downtime.',
					'seo_title' => 'Restaurant Seating Upholstery Dubai | Booths & Banquettes',
					'seo_desc'  => 'Restaurant seating upholstery in Dubai: booths, banquettes and chairs in commercial-grade fabrics, done around opening hours. Quote on WhatsApp.',
					'keyword'   => 'restaurant upholstery dubai',
					'intro'     => array( 'Restaurant seating takes heavy daily use. We re-upholster booths, banquettes and chairs in commercial-grade, easy-clean materials that stand up to spills.', 'Work is scheduled around your opening hours to avoid lost covers.' ),
					'benefits'  => array( $b( 'Commercial grade', 'Durable, cleanable materials.' ), $b( 'Minimal downtime', 'Work planned around service times.' ), $b( 'On-site options', 'Fixed banquettes re-covered in place.' ), $b( 'Refreshed brand', 'Update the look without a full refit.' ) ),
					'specs'     => array( 'Booths, banquettes and dining chairs', 'Commercial vinyl and performance fabrics', 'Foam replacement', 'On-site and workshop work' ),
					'uses'      => array( 'Restaurants and cafés', 'Hotel dining', 'Lounges and bars', 'Food courts' ),
					'faqs'      => array( array( 'Can you work while we are closed?', 'Yes, we schedule work around your closing times.' ), array( 'Can fixed booths be done on site?', 'Many fixed banquettes can be re-covered on site.' ), array( 'Which material is best?', 'Commercial vinyl and performance fabrics are easiest to clean.' ) ),
				),
				'car-seat-upholstery'           => array(
					'title'     => 'Car Seat Upholstery',
					'excerpt'   => 'Car seat re-covering and repairs in fabric and leather-look materials.',
					'seo_title' => 'Car Seat Upholstery Dubai | Seat Re-covering & Repair',
					'seo_desc'  => 'Car seat upholstery in Dubai: seat re-covering, repairs and custom interiors in fabric and leather-look. Quote on WhatsApp.',
					'keyword'   => 'car seat upholstery dubai',
					'intro'     => array( 'UAE sun and daily use crack and fade car seats. We re-cover and repair seats so your car interior looks sharp again.', 'Choose factory-style finishes or a custom look with contrast stitching.' ),
					'benefits'  => array( $b( 'Like-new interior', 'Fresh seats and trim.' ), $b( 'Custom styles', 'Contrast stitching and colours.' ), $b( 'Repairs', 'Tears, cracks and worn bolsters fixed.' ), $b( 'Resale value', 'A clean interior helps resale.' ) ),
					'specs'     => array( 'Fabric and leather-look materials', 'Full re-cover or panel repairs', 'Custom stitching options', 'Foam and bolster repairs' ),
					'uses'      => array( 'Family cars and SUVs', 'Classic cars', 'Fleet and company vehicles', 'Vans and buses' ),
					'faqs'      => array( array( 'How long does it take?', 'It depends on the vehicle and materials; we confirm when quoting.' ), array( 'Can you repair one seat only?', 'Yes, single-seat and panel repairs are possible.' ), array( 'Do you do headliners?', 'Ask us on WhatsApp with photos and we will advise.' ) ),
				),
				'outdoor-furniture-upholstery'  => array(
					'title'     => 'Outdoor Furniture Upholstery',
					'excerpt'   => 'Weather-ready cushions and covers for garden, pool and terrace furniture.',
					'seo_title' => 'Outdoor Furniture Upholstery Dubai | Garden & Pool Cushions',
					'seo_desc'  => 'Outdoor furniture upholstery in Dubai: UV-resistant cushions and covers for garden, pool and terrace furniture. Quote on WhatsApp.',
					'keyword'   => 'outdoor cushions dubai',
					'intro'     => array( 'Outdoor furniture faces intense sun, dust and humidity. We make cushions and covers in outdoor fabrics that resist fading and dry quickly.', 'Perfect for villa gardens, pool decks, terraces and hotel outdoor areas.' ),
					'benefits'  => array( $b( 'UV resistant', 'Outdoor fabrics that resist fading.' ), $b( 'Quick drying', 'Suitable foams for outdoor use.' ), $b( 'Made to fit', 'Cushions sized to your furniture.' ), $b( 'Fresh look', 'Revive tired outdoor seating.' ) ),
					'specs'     => array( 'Outdoor solution-dyed fabrics', 'Quick-dry foam options', 'Removable zipped covers', 'Custom sizes and shapes' ),
					'uses'      => array( 'Villa gardens', 'Pool loungers', 'Terraces and balconies', 'Hotel and beach clubs' ),
					'faqs'      => array( array( 'Will outdoor cushions fade?', 'Outdoor fabrics resist fading far better than indoor fabrics; storing them in extreme heat extends life further.' ), array( 'Can covers be removed for washing?', 'Yes, zipped covers are available.' ), array( 'Do you make cushions for any shape?', 'Yes, we make custom shapes and sizes.' ) ),
				),
				'cushion-pillow-upholstery'     => array(
					'title'     => 'Cushion & Pillow Upholstery',
					'excerpt'   => 'Custom cushions, pillows and floor seating made to your size and fabric.',
					'seo_title' => 'Cushion & Pillow Upholstery Dubai | Custom Cushions',
					'seo_desc'  => 'Custom cushions and pillows in Dubai: scatter cushions, seat pads, floor seating and majlis cushions made to measure. Quote on WhatsApp.',
					'keyword'   => 'custom cushions dubai',
					'intro'     => array( 'Cushions are the quickest way to refresh a room. We make scatter cushions, seat pads, bolsters and majlis floor seating to your size and fabric.', 'Coordinate them with your curtains and upholstery for a finished look.' ),
					'benefits'  => array( $b( 'Any size', 'Made to measure for your seating.' ), $b( 'Coordinated', 'Match curtains and sofas.' ), $b( 'Majlis seating', 'Floor cushions and backrests.' ), $b( 'Comfort options', 'Foam and fibre fillings.' ) ),
					'specs'     => array( 'Scatter cushions and bolsters', 'Seat pads and bench cushions', 'Majlis floor seating', 'Foam, fibre and feather-look fillings' ),
					'uses'      => array( 'Living rooms and bedrooms', 'Majlis', 'Window seats and benches', 'Cafés and hotels' ),
					'faqs'      => array( array( 'Can you use my own fabric?', 'Yes, share the fabric and sizes and we confirm quantities.' ), array( 'Do you make majlis cushions?', 'Yes, floor cushions and backrests are made to measure.' ), array( 'How quickly can cushions be made?', 'Turnaround depends on quantity; we confirm when quoting.' ) ),
				),
			),
		),
		'flooring'   => array(
			'title'     => 'Flooring',
			'excerpt'   => 'Wooden, vinyl, laminate, epoxy, sports and rubber flooring for homes and businesses — plus our specialist gym floors.',
			'seo_title' => 'Flooring Dubai | Wooden, Vinyl, Laminate & Epoxy',
			'seo_desc'  => 'Flooring supply and installation in Dubai & UAE: wooden, vinyl, laminate, epoxy, sports, rubber and gym flooring by Casa Vera Home. Quote on WhatsApp.',
			'keyword'   => 'flooring dubai',
			'intro'     => 'Every floor, one team — from warm wood and practical vinyl to seamless epoxy and our specialist gym and sports floors.',
			'children'  => array(
				'wooden-flooring'  => array(
					'title'     => 'Wooden Flooring',
					'excerpt'   => 'Engineered and solid wood floors, including herringbone and chevron patterns, supplied and installed.',
					'seo_title' => 'Wooden Flooring Dubai | Engineered Wood & Herringbone',
					'seo_desc'  => 'Wooden flooring in Dubai: engineered and solid wood, herringbone and chevron patterns for villas and apartments. Supply & installation. WhatsApp us.',
					'keyword'   => 'wooden flooring dubai',
					'intro'     => array( 'Wood brings natural warmth and value to any home. Engineered wood is the most stable choice for UAE conditions, with a real wood surface on a layered core.', 'Choose classic planks or statement patterns such as herringbone and chevron.' ),
					'benefits'  => array( $b( 'Natural warmth', 'Real wood character and feel.' ), $b( 'Stable', 'Engineered boards suit the UAE climate.' ), $b( 'Patterns', 'Herringbone, chevron and wide planks.' ), $b( 'Adds value', 'A premium upgrade for villas and apartments.' ) ),
					'specs'     => array( 'Engineered and solid wood', 'Oak and other species, various finishes', 'Plank, herringbone and chevron formats', 'Floating or glue-down installation' ),
					'uses'      => array( 'Living rooms and bedrooms', 'Villas and penthouses', 'Boutique hotels', 'Executive offices' ),
					'faqs'      => array( array( 'Is wood flooring suitable for Dubai?', 'Engineered wood is designed to be stable and is widely used in the UAE, with correct acclimatisation and installation.' ), array( 'Can wood go over tiles?', 'Often yes, depending on level and condition; we check on site.' ), array( 'Can it be refinished?', 'Many engineered floors can be lightly sanded and refinished.' ) ),
				),
				'vinyl-flooring'   => array(
					'title'     => 'Vinyl Flooring',
					'excerpt'   => 'Waterproof SPC and LVT vinyl planks and tiles — realistic wood and stone looks that are easy to maintain.',
					'seo_title' => 'Vinyl Flooring Dubai | SPC & LVT Waterproof Floors',
					'seo_desc'  => 'Vinyl flooring in Dubai: waterproof SPC and LVT planks in wood and stone looks for homes and offices. Fast installation. Quote on WhatsApp.',
					'keyword'   => 'vinyl flooring dubai',
					'intro'     => array( 'Vinyl flooring (SPC and LVT) gives the look of wood or stone with a waterproof, scratch-resistant surface that is easy to clean.', 'Click systems can often be installed over existing tiles, making it a fast upgrade for apartments and offices.' ),
					'benefits'  => array( $b( 'Waterproof', 'Suitable for kitchens and wet areas (product dependent).' ), $b( 'Realistic looks', 'Wood and stone effects.' ), $b( 'Fast install', 'Click systems over many existing floors.' ), $b( 'Low maintenance', 'Sweep and mop.' ) ),
					'specs'     => array( 'SPC rigid core and LVT', 'Click and glue-down systems', 'Integrated underlay options', 'Residential and commercial wear layers' ),
					'uses'      => array( 'Apartments and villas', 'Kitchens', 'Offices and retail', 'Rental upgrades' ),
					'faqs'      => array( array( 'Can vinyl go over tiles?', 'Often yes, if the tiles are level and sound.' ), array( 'Is vinyl flooring waterproof?', 'SPC and many LVT products are water-resistant to waterproof; we advise per product.' ), array( 'Vinyl or laminate?', 'Vinyl handles moisture better; laminate can be more budget-friendly in dry rooms.' ) ),
				),
				'laminate-flooring' => array(
					'title'     => 'Laminate Flooring',
					'excerpt'   => 'Durable, budget-friendly laminate in realistic wood designs for bedrooms, living rooms and offices.',
					'seo_title' => 'Laminate Flooring Dubai | Supply & Installation',
					'seo_desc'  => 'Laminate flooring in Dubai: durable, budget-friendly wood-look floors for bedrooms, living rooms and offices. Installed quickly. Quote on WhatsApp.',
					'keyword'   => 'laminate flooring dubai',
					'intro'     => array( 'Laminate combines a realistic wood image with a tough wear layer, making it an affordable and hard-wearing choice for dry rooms.', 'Floating click installation over underlay keeps projects quick and clean.' ),
					'benefits'  => array( $b( 'Budget-friendly', 'Wood looks at a lower cost.' ), $b( 'Scratch resistant', 'Tough surface for busy homes.' ), $b( 'Quick install', 'Floating click systems.' ), $b( 'Many designs', 'Oak, walnut, grey and more.' ) ),
					'specs'     => array( 'AC-rated wear classes', 'Various thicknesses', 'Underlay for comfort and sound', 'Skirting and profiles included on request' ),
					'uses'      => array( 'Bedrooms and living rooms', 'Offices', 'Rental apartments', 'Retail spaces' ),
					'faqs'      => array( array( 'Can laminate go in kitchens?', 'Water-resistant laminates exist, but vinyl is usually better for wet areas.' ), array( 'Do you remove old flooring?', 'Yes, removal can be included.' ), array( 'How long does installation take?', 'An average apartment room is usually done in a day.' ) ),
				),
				'epoxy-flooring'   => array(
					'title'     => 'Epoxy Flooring',
					'excerpt'   => 'Seamless epoxy floors for garages, warehouses, showrooms and kitchens — tough, hygienic and easy to clean.',
					'seo_title' => 'Epoxy Flooring Dubai | Garage, Warehouse & Showroom',
					'seo_desc'  => 'Epoxy flooring in Dubai for garages, warehouses, showrooms and commercial kitchens. Seamless, durable and easy to clean. Quote on WhatsApp.',
					'keyword'   => 'epoxy flooring dubai',
					'intro'     => array( 'Epoxy creates a seamless, glossy or satin surface that resists stains, chemicals and heavy traffic — ideal for garages, warehouses and showrooms.', 'Surface preparation is key; we grind and prime the concrete before applying coatings.' ),
					'benefits'  => array( $b( 'Seamless', 'No joints for dirt to collect.' ), $b( 'Tough', 'Handles vehicles and heavy traffic.' ), $b( 'Hygienic', 'Easy to clean and chemical resistant.' ), $b( 'Decorative', 'Solid colours, flakes and metallic effects.' ) ),
					'specs'     => array( 'Concrete grinding and priming', 'Self-levelling and roller-applied systems', 'Anti-slip additives', 'Flake and metallic finishes' ),
					'uses'      => array( 'Villa garages', 'Warehouses and workshops', 'Showrooms', 'Commercial kitchens' ),
					'faqs'      => array( array( 'How long before I can use the floor?', 'Curing times depend on the system and temperature; we give exact times on the day.' ), array( 'Is epoxy slippery?', 'Anti-slip additives can be added for safety.' ), array( 'Can epoxy go over tiles?', 'Usually epoxy is applied on prepared concrete; we assess existing floors on site.' ) ),
				),
				'sports-flooring'  => array(
					'title'     => 'Sports Flooring',
					'excerpt'   => 'Floors for courts, halls and studios — vinyl sports floors, rubber and turf for schools, clubs and villas.',
					'seo_title' => 'Sports Flooring Dubai | Courts, Halls & Studios',
					'seo_desc'  => 'Sports flooring in Dubai for courts, school halls, studios and clubs: vinyl sports floors, rubber and turf. Supply & installation. WhatsApp us.',
					'keyword'   => 'sports flooring dubai',
					'intro'     => array( 'Sports floors are engineered for grip, shock absorption and ball bounce. We supply and install flooring for multi-purpose halls, school gyms, studios and courts.', 'For fitness areas, see our full range of gym flooring systems.' ),
					'benefits'  => array( $b( 'Player safety', 'Shock absorption reduces strain.' ), $b( 'Right grip', 'Surfaces suited to each sport.' ), $b( 'Line markings', 'Courts marked for your activities.' ), $b( 'Indoor & outdoor', 'Vinyl indoors, turf and EPDM outdoors.' ) ),
					'specs'     => array( 'Cushioned vinyl sports floors', 'Rubber sports surfaces', 'Sports and gym turf', 'Court line marking' ),
					'uses'      => array( 'School sports halls', 'Multi-purpose courts', 'Dance and fitness studios', 'Clubs and academies' ),
					'faqs'      => array( array( 'Which floor for a multi-purpose hall?', 'Cushioned vinyl sports flooring is a versatile choice; we recommend based on activities.' ), array( 'Do you mark court lines?', 'Yes, line marking can be included.' ), array( 'Do you do outdoor courts?', 'Ask us on WhatsApp with your site details and we will advise.' ) ),
				),
				'rubber-flooring'  => array(
					'title'     => 'Rubber Flooring',
					'excerpt'   => 'Hard-wearing rubber floors for gyms, commercial spaces, play areas and outdoor zones.',
					'seo_title' => 'Rubber Flooring Dubai | Tiles, Rolls & EPDM',
					'seo_desc'  => 'Rubber flooring in Dubai: tiles, rolls and EPDM for gyms, commercial areas, play spaces and outdoor zones. Supply & installation. WhatsApp us.',
					'keyword'   => 'rubber flooring dubai',
					'intro'     => array( 'Rubber is slip-resistant, shock-absorbing and extremely durable — ideal wherever floors take impact or heavy use.', 'Explore our detailed gym rubber flooring range for tiles, rolls, EPDM and platforms.' ),
					'benefits'  => array( $b( 'Durable', 'Handles heavy traffic and impact.' ), $b( 'Slip-resistant', 'Safer underfoot.' ), $b( 'Quiet', 'Reduces impact noise.' ), $b( 'Versatile', 'Indoor and outdoor systems.' ) ),
					'specs'     => array( 'Rubber tiles and rolls', 'EPDM colour and outdoor systems', 'Various thicknesses', 'Loose-lay, interlocking or bonded' ),
					'uses'      => array( 'Gyms and fitness rooms', 'Play areas', 'Commercial corridors and ramps', 'Outdoor terraces' ),
					'faqs'      => array( array( 'Is rubber flooring good for homes?', 'Yes, especially for home gyms, playrooms and garages.' ), array( 'Can rubber go outdoors?', 'UV-stable EPDM systems are designed for outdoor use.' ), array( 'Which thickness do I need?', 'It depends on use; our gym flooring pages include a thickness guide.' ) ),
				),
				'gym-flooring'     => array(
					'title'     => 'Gym Flooring',
					'excerpt'   => 'Our specialist gym flooring range — rubber, EPDM, turf, platforms and acoustic systems for every gym.',
					'seo_title' => 'Gym Flooring Services | Casa Vera Home Flooring',
					'seo_desc'  => 'Gym flooring from Casa Vera Home: rubber tiles, rolls, EPDM, sled turf, deadlift platforms and acoustic systems. See the full range and get a quote.',
					'keyword'   => 'gym flooring services',
					'intro'     => array( 'Gym flooring is our specialist range, with dedicated pages for every system — from rubber tiles and rolls to sled turf, deadlift platforms and acoustic underlays.', 'Browse the full gym flooring range or send your room size on WhatsApp for a recommendation.' ),
					'benefits'  => array( $b( 'Specialist range', '15 gym flooring systems.' ), $b( 'Zoned design', 'The right floor for each training zone.' ), $b( 'Free samples', 'See and feel before you decide.' ), $b( 'All emirates', 'Supply and installation across the UAE.' ) ),
					'specs'     => array( 'Rubber tiles, rolls and EPDM', 'Gym turf and sled track', 'Deadlift platforms', 'Acoustic and anti-vibration systems' ),
					'uses'      => array( 'Home gyms', 'Commercial gyms', 'CrossFit boxes', 'Hotel and tower gyms' ),
					'faqs'      => array( array( 'Where can I see all gym flooring options?', 'Visit our Gym Flooring Products page for the full range with specifications.' ), array( 'Do you offer free samples?', 'Yes, we bring samples to your site during the free survey.' ), array( 'Do you install outside Dubai?', 'Yes, across all seven emirates.' ) ),
				),
			),
		),
	);

	$pages = array();
	$pages['interiors'] = array(
		'title'     => 'Interiors & Home Services',
		'menu'      => 'Interiors',
		'type'      => 'hub',
		'hub_of'    => 'interiors',
		'excerpt'   => 'Curtains, blinds, carpets, wallpaper, upholstery and flooring from Casa Vera Home — measured, made and installed across Dubai and the UAE.',
		'seo_title' => 'Interiors & Home Services Dubai | Casa Vera Home',
		'seo_desc'  => 'Casa Vera Home interior services in Dubai & UAE: curtains, blinds, carpets, wallpaper, upholstery and flooring. Free measurement. Quote on WhatsApp.',
		'keyword'   => 'interior services dubai',
		'aliases'   => array( 'interiors', 'home services' ),
	);
	$order = 1;
	foreach ( $categories as $cat_slug => $cat ) {
		$pages[ $cat_slug ] = array(
			'title'     => $cat['title'],
			'type'      => 'hub',
			'hub_of'    => 'interior-category',
			'order'     => $order++,
			'excerpt'   => $cat['excerpt'],
			'seo_title' => $cat['seo_title'],
			'seo_desc'  => $cat['seo_desc'],
			'keyword'   => $cat['keyword'],
			'intro'     => $cat['intro'],
			'aliases'   => array( $cat_slug ),
		);
		$child_order = 1;
		foreach ( $cat['children'] as $slug => $child ) {
			$pages[ $slug ] = array_merge(
				array(
					'parent'   => $cat_slug,
					'type'     => 'interior',
					'category' => $cat['title'],
					'order'    => $child_order++,
					'adopt'    => true,
					'aliases'  => array( str_replace( '-', ' ', $slug ) ),
				),
				$child
			);
		}
	}
	return $pages;
}

/**
 * Slugs of the six interior category pages (used by the home page section).
 *
 * @return string[]
 */
function dgf_interior_category_slugs() {
	return array( 'curtains', 'blinds', 'carpets', 'wallpaper', 'upholstery', 'flooring' );
}
