<?php
/**
 * Product page content: curtains and blinds.
 * Text here is only the starting content — after import, edit everything in the block editor.
 *
 * Keys: name, parent, img (bundled image group), media (existing media-library filename prefix),
 * seo_title, seo_desc, kicker, h1, lead, what_title, paras, checks, opt_title, tiles, faqs, related.
 *
 * @package dce-vibe
 */

defined( 'ABSPATH' ) || exit;

function dce_products() {
	if ( 'dbh' === dce_profile() ) {
		return dbh_services();
	}
	return array(

		/* ------------------------------- CURTAINS ------------------------------- */

		'wave-curtains'           => array(
			'name'       => 'Wave Curtains',
			'parent'     => 'curtains',
			'img'        => 'wave-curtains',
			'media'      => 'wave-curtain',
			'seo_title'  => 'Wave Curtains Dubai | Made-to-Measure S-Fold | Free Visit',
			'seo_desc'   => 'Made-to-measure wave (S-fold) curtains in Dubai and the UAE. Sheer and blackout fabrics, ceiling or wall tracks, motor-ready. Free home visit & measurement.',
			'card'       => 'Soft, even S-folds on a ceiling track — the modern favourite for apartments and villas.',
			'kicker'     => 'Curtains · Dubai &amp; UAE',
			'h1'         => '<em>Wave</em> curtains in Dubai',
			'lead'       => 'Even, flowing S-shaped folds from ceiling to floor. Wave curtains give a calm, hotel-style finish and glide smoothly on a slim track — ideal for floor-to-ceiling glass.',
			'what_title' => 'What makes <em>wave curtains</em> different?',
			'paras'      => array(
				'Wave curtains hang from carriers spaced at equal distances on a dedicated track, so the fabric forms soft, identical waves front and back. There are no bunched pleats and no visible hooks — just a clean, continuous line.',
				'Because the folds are controlled, wave curtains stack neatly to the side and leave more of the glass open. That makes them a natural choice for Dubai apartments with full-height windows, sliding balcony doors and long villa living rooms.',
				'We make wave curtains in sheers, linens, dim-out and full blackout fabrics, and can layer a sheer and a blackout on a double track for day and night control.',
			),
			'checks'     => array(
				'Uniform S-folds that look tidy from inside and outside',
				'Ceiling-mounted or wall-mounted tracks, including recessed pelmets',
				'Sheer, linen, dim-out and blackout fabrics',
				'Double tracks for a sheer + blackout layer',
				'Motor-ready tracks for remote, app or smart-home control',
			),
			'opt_title'  => 'Options for your <em>wave curtains</em>',
			'tiles'      => array(
				array( 'Fullness', 'Choose a softer or deeper wave by adjusting carrier spacing and fabric fullness to suit the window and fabric weight.' ),
				array( 'Sheer layer', 'Voile and linen-look sheers soften harsh daylight while keeping the view — perfect behind a blackout layer.' ),
				array( 'Blackout lining', 'Lined or fully blackout fabrics for bedrooms, media rooms and anyone who sleeps during the day.' ),
				array( 'Tracks', 'Slim aluminium tracks in white, black or silver, fixed to ceiling, wall or a recess above the window.' ),
				array( 'Motorization', 'Quiet motors with remote or app control — ideal for wide spans and high windows.' ),
				array( 'Finishing', 'Weighted hems, neat side returns and floor-skimming or puddled lengths, made to your measurements.' ),
			),
			'faqs'       => array(
				array( 'Are wave curtains good for floor-to-ceiling windows?', 'Yes. Wave curtains are made for large glass: the folds stay even across wide spans, they stack compactly to the side and they work well on ceiling tracks right up to the ceiling line.' ),
				array( 'Can wave curtains be blackout?', 'Yes. We make wave curtains in blackout fabric or add a blackout lining. For full flexibility, many clients choose a double track with a sheer wave in front of a blackout wave.' ),
				array( 'Can I motorize wave curtains later?', 'If you choose a motor-ready track we can add a motor later. Tell us during the home visit and we will plan the power point and track type.' ),
				array( 'What is the difference between wave and pinch pleat curtains?', 'Wave curtains form soft, continuous S-folds on a special track and suit modern interiors. Pinch pleat curtains have stitched pleats at the top and a more tailored, classic look.' ),
			),
			'related'    => array( 'pinch-pleat-curtains', 'sheer-curtains', 'blackout-curtains', 'motorized-curtains' ),
		),

		'pinch-pleat-curtains'    => array(
			'name'       => 'Pinch Pleat Curtains',
			'parent'     => 'curtains',
			'img'        => 'pinch-pleat-curtains',
			'media'      => 'pinch-pleat',
			'seo_title'  => 'Pinch Pleat Curtains Dubai | Tailored Double & Triple Pleat',
			'seo_desc'   => 'Tailored pinch pleat curtains made to measure in Dubai. Double, triple and French pleats, lined or blackout, on tracks or rods. Free home visit across the UAE.',
			'card'       => 'Tailored pleats with a classic, structured drape for living rooms, bedrooms and majlis.',
			'kicker'     => 'Curtains · Dubai &amp; UAE',
			'h1'         => '<em>Pinch pleat</em> curtains in Dubai',
			'lead'       => 'Hand-finished pleats that hold their shape and fall in crisp, elegant columns. A timeless heading for formal living rooms, majlis and master bedrooms.',
			'what_title' => 'The tailored look of <em>pinch pleats</em>',
			'paras'      => array(
				'Pinch pleat curtains are gathered into evenly spaced groups of folds stitched at the top. The pleats are reinforced with buckram, so the curtain keeps a structured, upright shape every time it is opened and closed.',
				'Choose double pleats for a lighter look, triple pleats for a fuller, more luxurious drape, or French and goblet variations for formal rooms. They work on curtain tracks or decorative rods with rings.',
				'We pair pinch pleats with linings for insulation and privacy, or with blackout for bedrooms — a practical choice for the strong UAE sun.',
			),
			'checks'     => array(
				'Double, triple, French and goblet pleat styles',
				'Structured heading that keeps its shape',
				'Lined, interlined or blackout options',
				'Hangs from tracks or decorative rods with rings',
				'Pairs beautifully with a sheer underlayer',
			),
			'opt_title'  => 'Pleats, linings &amp; <em>hardware</em>',
			'tiles'      => array(
				array( 'Double pleat', 'Two folds per pleat — clean and lighter, a good fit for contemporary rooms.' ),
				array( 'Triple pleat', 'Three folds per pleat for a fuller, more formal drape and a classic finish.' ),
				array( 'Linings', 'Standard, thermal or blackout linings protect fabrics from sun fade and improve privacy.' ),
				array( 'Rods &amp; rings', 'Decorative metal or wood rods with finials when the hardware is part of the look.' ),
				array( 'Tracks', 'Ceiling or wall tracks for a cleaner line, including motorized tracks.' ),
				array( 'Tiebacks', 'Fabric, rope or metal holdbacks to frame the window when curtains are open.' ),
			),
			'faqs'       => array(
				array( 'Are pinch pleat curtains still in style?', 'Yes. Pinch pleats are a classic heading that suits traditional, transitional and many modern interiors, especially in formal living rooms and majlis.' ),
				array( 'Can pinch pleat curtains be motorized?', 'Yes. Pinch pleat curtains can hang on a motorized track with standard gliders, so they open and close at the touch of a button.' ),
				array( 'Should I choose double or triple pleats?', 'Double pleats look lighter and suit simpler fabrics. Triple pleats use more fabric and give a richer, fuller drape. We bring samples so you can compare in your room.' ),
				array( 'Do you add linings?', 'Yes. We recommend a lining for most pinch pleat curtains to protect the fabric from strong sunlight, add body and improve privacy. Blackout lining is available for bedrooms.' ),
			),
			'related'    => array( 'wave-curtains', 'american-style-curtains', 'blackout-curtains', 'sheer-curtains' ),
		),

		'eyelet-curtains'         => array(
			'name'       => 'Eyelet Curtains',
			'parent'     => 'curtains',
			'img'        => 'eyelet-curtains',
			'media'      => 'eyelet',
			'seo_title'  => 'Eyelet Curtains Dubai | Grommet Curtains Made to Measure',
			'seo_desc'   => 'Made-to-measure eyelet (grommet) curtains in Dubai and the UAE. Metal rings in chrome, black or gold, blackout or sheer fabrics. Free measurement visit.',
			'card'       => 'Metal rings that slide on a rod — relaxed, modern and easy to open and close.',
			'kicker'     => 'Curtains · Dubai &amp; UAE',
			'h1'         => '<em>Eyelet</em> curtains in Dubai',
			'lead'       => 'Smooth, deep folds created by metal rings punched into the heading. Eyelet curtains glide easily on a decorative rod and give rooms a relaxed, contemporary feel.',
			'what_title' => 'Why choose <em>eyelet curtains</em>?',
			'paras'      => array(
				'Eyelet (grommet) curtains have metal rings set into a stiffened heading. The rod passes straight through the rings, creating large, uniform folds without hooks or gliders.',
				'They are simple to use every day, look neat in bedrooms, kids’ rooms and living rooms, and make the curtain rod part of the design. Rings come in finishes to match your hardware — chrome, matte black, brass or antique gold.',
				'We make eyelet curtains to the exact drop of your window in plain, textured, printed, sheer and blackout fabrics.',
			),
			'checks'     => array(
				'Deep, even folds without hooks',
				'Rings in chrome, black, brass or gold finishes',
				'Easy to open and close every day',
				'Blackout and thermal fabric options',
				'Made to your exact width and drop',
			),
			'opt_title'  => 'Choose your <em>eyelet finish</em>',
			'tiles'      => array(
				array( 'Ring finishes', 'Match rings to your rods, handles and lighting: chrome, black, brass, gold or white.' ),
				array( 'Fabrics', 'Linen-look, velvet, cotton blends, prints and sheers from our fabric catalogues.' ),
				array( 'Blackout', 'Blackout fabric or lining for bedrooms facing strong morning or afternoon sun.' ),
				array( 'Rods', 'Single or double rods with matching finials and wall or ceiling brackets.' ),
			),
			'faqs'       => array(
				array( 'Are eyelet curtains good for blackout?', 'Yes. Eyelet curtains can be made in blackout fabric. A small amount of light can pass above the rod, so for complete darkness we may suggest a ceiling-fixed rod or a track-based heading.' ),
				array( 'Can eyelet curtains go on a track?', 'Eyelet curtains are designed for rods. If you prefer a ceiling track, wave or pinch pleat headings give a similar clean look on a track.' ),
				array( 'What colours do the eyelets come in?', 'Common finishes include chrome, matte black, brass, gold and white. We help you match them to the rod and room.' ),
				array( 'Do you install the curtain rods?', 'Yes. We supply and install rods, brackets and finials as part of the job, measured for your window.' ),
			),
			'related'    => array( 'wave-curtains', 'blackout-curtains', 'kids-curtains', 'sheer-curtains' ),
		),

		'american-style-curtains' => array(
			'name'       => 'American Style Curtains',
			'parent'     => 'curtains',
			'img'        => 'american-style-curtains',
			'media'      => 'american',
			'seo_title'  => 'American Style Curtains Dubai | Luxury Drapes & Valances',
			'seo_desc'   => 'Luxury American style curtains in Dubai: full drapes, swag valances, tiebacks and layered sheers, made to measure for villas and majlis. Free home visit.',
			'card'       => 'Generous drapes, valances and tiebacks for grand villas, majlis and master suites.',
			'kicker'     => 'Curtains · Dubai &amp; UAE',
			'h1'         => '<em>American style</em> curtains in Dubai',
			'lead'       => 'Full, layered drapery with rich fabrics, valances and tiebacks. American style curtains bring a grand, hotel-suite atmosphere to villas, majlis and formal living rooms.',
			'what_title' => 'Luxury, <em>layered</em> drapery',
			'paras'      => array(
				'American style curtains are about generosity: plenty of fabric fullness, floor-length or puddled drops, and layers of sheer, main curtain and decorative valance or pelmet.',
				'They suit high ceilings and large windows found in many Dubai villas, and pair well with classic and transitional furniture. Trims, tassels, contrast borders and embroidered fabrics complete the look.',
				'Every piece is made to measure so that the proportions of valance, drop and fullness are right for your ceiling height and window.',
			),
			'checks'     => array(
				'Swag, pleated and box valances or upholstered pelmets',
				'Layered sheer + main curtain combinations',
				'Velvet, jacquard, silk-look and embroidered fabrics',
				'Tiebacks, trims, tassels and contrast borders',
				'Ideal for villas, majlis and master bedrooms',
			),
			'opt_title'  => 'Build your <em>signature drape</em>',
			'tiles'      => array(
				array( 'Valances', 'Swag-and-tail, pleated or box valances to crown the window.' ),
				array( 'Pelmets', 'Upholstered or fabric-covered pelmets that hide tracks and add structure.' ),
				array( 'Layers', 'Sheers for daytime softness and lined drapes for privacy at night.' ),
				array( 'Trims', 'Fringes, tassels, beading and contrast banding for a tailored finish.' ),
			),
			'faqs'       => array(
				array( 'What are American style curtains?', 'It is a term used in the UAE for full, luxurious drapery — usually floor-length curtains with valances or pelmets, tiebacks and a sheer layer, in rich fabrics.' ),
				array( 'Are they suitable for apartments?', 'Yes, in a simplified form. For lower ceilings we keep valances slimmer and drops cleaner so the room does not feel heavy.' ),
				array( 'Can you match existing furniture fabrics?', 'Bring a fabric swatch or photo to the home visit — we compare it against our catalogues to find matching or complementary fabrics.' ),
				array( 'How long does making take?', 'It depends on fabric availability and the amount of detailing. We confirm a clear timeline in your quotation before work begins.' ),
			),
			'related'    => array( 'pinch-pleat-curtains', 'roman-curtains', 'sheer-curtains', 'blackout-curtains' ),
		),

		'roman-curtains'          => array(
			'name'       => 'Roman Curtains',
			'parent'     => 'curtains',
			'img'        => 'roman-curtains',
			'media'      => 'roman-curtains',
			'seo_title'  => 'Roman Curtains Dubai | Fabric Roman Shades Made to Measure',
			'seo_desc'   => 'Fabric Roman curtains (Roman shades) made to measure in Dubai. Flat, hobbled and relaxed folds, lined or blackout, chain or motorized. Free home visit.',
			'card'       => 'Fabric that folds up in soft, tailored layers — curtain softness with a blind’s neat footprint.',
			'kicker'     => 'Curtains · Dubai &amp; UAE',
			'h1'         => '<em>Roman</em> curtains in Dubai',
			'lead'       => 'Fabric that lifts into neat horizontal folds and sits inside or above the window. Roman curtains combine the softness of curtains with the tidy footprint of a blind.',
			'what_title' => 'The soft structure of <em>Roman curtains</em>',
			'paras'      => array(
				'Roman curtains (also called Roman shades) are flat fabric panels with rods sewn into the back. When raised, the fabric stacks into crisp folds; when lowered, it lies smooth so you can enjoy the full pattern of the fabric.',
				'They are a great choice for kitchens, studies, bay windows and bedrooms where floor-length curtains would get in the way — and they can be layered under side curtains for a decorator finish.',
				'We make them in plains, prints, linens and textures, with standard, thermal or blackout linings and chain, cordless or motorized control.',
			),
			'checks'     => array(
				'Flat, hobbled (cascade) or relaxed fold styles',
				'Show off patterned and printed fabrics',
				'Standard, thermal or blackout linings',
				'Chain, cordless or motorized operation',
				'Fits inside the recess or above the window',
			),
			'opt_title'  => 'Fold styles &amp; <em>controls</em>',
			'tiles'      => array(
				array( 'Flat fold', 'Crisp, tailored folds that stack neatly — the classic modern Roman.' ),
				array( 'Hobbled fold', 'Soft, cascading loops of fabric even when lowered, for a more luxurious look.' ),
				array( 'Relaxed', 'A gentle curve at the bottom edge — informal and elegant.' ),
				array( 'Controls', 'Side chain, child-safe cordless or quiet motor with remote.' ),
			),
			'faqs'       => array(
				array( 'Are Roman curtains the same as Roman blinds?', 'They are closely related. We use “Roman curtains” for decorative, fabric-led designs from our curtain fabrics, and “Roman blinds” for simpler blind-fabric versions. Both are made to measure.' ),
				array( 'Can Roman curtains be blackout?', 'Yes, with a blackout lining. For maximum darkness we can mount them outside the recess so they overlap the window frame.' ),
				array( 'Are they suitable for kitchens and bathrooms?', 'Yes, with the right fabric. We recommend easy-care, moisture-tolerant fabrics for wet areas.' ),
				array( 'Can I use my own fabric?', 'Often yes — share the fabric details during the home visit and we will check if it is suitable for a Roman construction.' ),
			),
			'related'    => array( 'roman-blinds', 'american-style-curtains', 'pinch-pleat-curtains', 'blackout-curtains' ),
		),

		'blackout-curtains'       => array(
			'name'       => 'Blackout Curtains',
			'parent'     => 'curtains',
			'img'        => 'blackout-curtains',
			'media'      => 'blackout-curtain',
			'seo_title'  => 'Blackout Curtains Dubai | Made-to-Measure Room Darkening',
			'seo_desc'   => 'Made-to-measure blackout curtains in Dubai for bedrooms, nurseries and media rooms. Blocks light and heat, wave or pinch pleat, motor-ready. Free home visit.',
			'card'       => 'Block light and heat for better sleep — made to overlap the window properly.',
			'kicker'     => 'Curtains · Dubai &amp; UAE',
			'h1'         => '<em>Blackout</em> curtains in Dubai',
			'lead'       => 'Sleep through bright Dubai mornings. Our made-to-measure blackout curtains block light and solar heat, and are cut to overlap the window so light does not leak around the edges.',
			'what_title' => 'Real darkness, <em>made to measure</em>',
			'paras'      => array(
				'Ready-made blackout curtains rarely fit UAE windows well, and gaps at the top and sides let light in. We measure each window and plan the track position, width and drop so the curtain overlaps the opening on all sides.',
				'Blackout curtains also help keep rooms cooler by reflecting solar heat, reduce glare on screens and add privacy at night — useful in high-rise apartments and villas with large glazing.',
				'Choose a fabric that is blackout on its own, or any decorative fabric with a separate blackout lining. Layer a sheer in front for softer daylight.',
			),
			'checks'     => array(
				'Planned overlap to stop light leaking at the edges',
				'Blocks glare and solar heat',
				'Blackout fabrics or blackout linings',
				'Wave, pinch pleat or eyelet headings',
				'Ideal for bedrooms, nurseries and media rooms',
			),
			'opt_title'  => 'Ways to make a room <em>truly dark</em>',
			'tiles'      => array(
				array( 'Ceiling tracks', 'Mounting at the ceiling stops light escaping above the curtain.' ),
				array( 'Side returns', 'Curtains that wrap back to the wall close the side gaps.' ),
				array( 'Blackout lining', 'Turn almost any decorative fabric into a blackout curtain.' ),
				array( 'Layering', 'Combine with a blackout roller blind for complete darkness in bedrooms.' ),
			),
			'faqs'       => array(
				array( 'Do blackout curtains block 100% of light?', 'The fabric itself blocks light. How dark the room gets depends on the fitting — which is why we plan ceiling tracks, overlaps and side returns during the home visit.' ),
				array( 'Do blackout curtains keep rooms cooler?', 'Yes. Blackout fabrics and linings reduce solar heat coming through the glass, which helps air-conditioned rooms stay comfortable.' ),
				array( 'Can blackout curtains look stylish?', 'Absolutely. Blackout can be a lining behind any fabric, so you are not limited to plain blackout material.' ),
				array( 'Ready-made or made to measure?', 'Made to measure gives the right width and drop for your window and avoids light gaps. We explain the difference in our blog guide on ready-made vs made-to-measure blackout curtains.' ),
			),
			'related'    => array( 'blackout-roller-blinds', 'wave-curtains', 'motorized-curtains', 'sheer-curtains' ),
		),

		'sheer-curtains'          => array(
			'name'       => 'Sheer Curtains',
			'parent'     => 'curtains',
			'img'        => 'sheer-curtains',
			'media'      => 'sheer',
			'seo_title'  => 'Sheer Curtains Dubai | Voile, Linen & Chiffon Made to Measure',
			'seo_desc'   => 'Sheer curtains in Dubai made to measure: voile, linen-look and chiffon sheers that soften sunlight and add daytime privacy. Wave or pinch pleat. Free visit.',
			'card'       => 'Voile and linen-look sheers that soften strong sunlight and keep the view.',
			'kicker'     => 'Curtains · Dubai &amp; UAE',
			'h1'         => '<em>Sheer</em> curtains in Dubai',
			'lead'       => 'Light, airy fabrics that filter harsh sunlight, cut glare and give daytime privacy — while keeping your view of the city, sea or garden.',
			'what_title' => 'Soft daylight, <em>all day</em>',
			'paras'      => array(
				'Sheer curtains are the everyday layer in most Dubai homes. They diffuse the strong sun into a soft glow, protect floors and furniture from fading, and stop neighbours seeing in during the day.',
				'We offer classic voiles, textured linen-look sheers and fine chiffons in whites, creams and greige tones, made up as wave or pinch pleat curtains on tracks or rods.',
				'For night-time privacy, pair your sheer with a blackout or lined curtain on a double track — or with a roller blind behind.',
			),
			'checks'     => array(
				'Voile, linen-look and chiffon sheers',
				'Diffuses glare and protects interiors from fading',
				'Daytime privacy without losing the view',
				'Wave or pinch pleat headings, weighted hems',
				'Pairs with blackout curtains on double tracks',
			),
			'opt_title'  => 'Choosing a <em>sheer fabric</em>',
			'tiles'      => array(
				array( 'Voile', 'Fine, smooth and airy — the lightest look with good light filtering.' ),
				array( 'Linen-look', 'Natural texture with a relaxed, contemporary feel; slightly more privacy.' ),
				array( 'Chiffon', 'Soft and fluid with a gentle sheen, beautiful in formal rooms.' ),
				array( 'Patterned sheers', 'Subtle stripes, embroidery and burn-out designs for character.' ),
			),
			'faqs'       => array(
				array( 'Do sheer curtains give privacy?', 'During the day, yes — it is harder to see in from outside when it is brighter outside than inside. At night, add a lined or blackout layer for full privacy.' ),
				array( 'Which sheer fabric is best for Dubai sun?', 'Linen-look and denser voiles filter more light and glare. We bring samples so you can test them against your windows.' ),
				array( 'Can sheers be motorized?', 'Yes. Sheers on a motorized track are popular for wide windows and high ceilings, often on a double track with a blackout layer.' ),
				array( 'How do I clean sheer curtains?', 'Most sheers can be gently washed or dry-cleaned depending on fabric. See our care guide on cleaning curtains and blinds in Dubai.' ),
			),
			'related'    => array( 'wave-curtains', 'blackout-curtains', 'pinch-pleat-curtains', 'motorized-curtains' ),
		),

		'motorized-curtains'      => array(
			'name'       => 'Motorized Curtains',
			'parent'     => 'curtains',
			'img'        => 'motorized-curtains',
			'media'      => 'motorized',
			'seo_title'  => 'Motorized Curtains Dubai | Electric & Smart Curtains',
			'seo_desc'   => 'Motorized and electric curtains in Dubai: remote, app and smart-home control for wave, pinch pleat and sheer curtains. Wired or wire-free motors. Free visit.',
			'card'       => 'Open and close with a remote, app or voice — perfect for wide glass and high windows.',
			'kicker'     => 'Curtains · Dubai &amp; UAE',
			'h1'         => '<em>Motorized</em> curtains in Dubai',
			'lead'       => 'Curtains that open with a tap, a remote, a schedule or your voice. Motorized tracks make wide windows, high ceilings and double layers effortless.',
			'what_title' => 'Smart control for <em>every window</em>',
			'paras'      => array(
				'A motorized curtain uses a quiet motor fitted to the track. You can open and close sheers and blackouts separately, set schedules for sunrise and sunset, and group several windows together.',
				'Motorization is especially useful for large villa windows, double-height living rooms, wide balcony glass and rooms where curtains are hard to reach. It also protects fabrics from being pulled by hand.',
				'We offer wired motors and wire-free (battery) motor options. Ask for our motor brochure on the <a href="/catalogue/">catalogues page</a>.',
			),
			'checks'     => array(
				'Remote, wall switch, app and smart-home options',
				'Schedules for sunrise, sunset and away mode',
				'Wired or wire-free motor options',
				'Works with wave, pinch pleat and sheer curtains',
				'Separate control of sheer and blackout layers',
			),
			'opt_title'  => 'Motorization <em>options</em>',
			'tiles'      => array(
				array( 'Wired motors', 'Powered from a nearby socket or concealed power point — best planned before painting.' ),
				array( 'Wire-free motors', 'Rechargeable motors for existing homes where adding power is difficult.' ),
				array( 'Controls', 'Handheld remotes, wall switches, smartphone apps and voice assistants.' ),
				array( 'Double tracks', 'Independent motors for sheer and blackout layers.' ),
			),
			'faqs'       => array(
				array( 'Do motorized curtains need a power point?', 'Wired motors need power near the track. Wire-free motors run on a rechargeable battery, so they are a good option for existing homes.' ),
				array( 'Can motorized curtains work with smart-home systems?', 'Many motors can connect to apps and popular smart-home platforms. We confirm compatibility during the home visit.' ),
				array( 'Can I still open the curtains by hand?', 'Most motor systems allow gentle manual operation or have a manual override if power is off.' ),
				array( 'Are motorized curtains noisy?', 'Modern curtain motors are quiet — comfortable for bedrooms and living rooms.' ),
			),
			'related'    => array( 'wave-curtains', 'sheer-curtains', 'blackout-curtains', 'cinema-curtains' ),
		),

		'beaded-curtains'         => array(
			'name'       => 'Beaded Curtains',
			'parent'     => 'curtains',
			'img'        => 'beaded-curtains',
			'media'      => 'beaded',
			'seo_title'  => 'Beaded Curtains Dubai | Crystal & Glass Bead Dividers',
			'seo_desc'   => 'Beaded curtains in Dubai: crystal, glass and string bead curtains for room dividers, doorways and décor. Made to size and installed. Free home visit.',
			'card'       => 'Crystal, glass and string beads that divide space while letting light through.',
			'kicker'     => 'Curtains · Dubai &amp; UAE',
			'h1'         => '<em>Beaded</em> curtains in Dubai',
			'lead'       => 'Shimmering crystal, glass and string bead curtains to divide open-plan spaces, frame doorways and add sparkle to villas, salons and events.',
			'what_title' => 'Light-catching <em>room dividers</em>',
			'paras'      => array(
				'Beaded curtains define a space without closing it off. Light and air pass through, so open-plan living rooms, dining areas and entrances stay bright while feeling more intimate.',
				'Choose clear or tinted crystal for a glamorous look, glass beads in gold and champagne tones, or soft string and tassel curtains for a relaxed, natural feel.',
				'We supply and install beaded curtains cut to the width and drop you need, on ceiling tracks or decorative rails.',
			),
			'checks'     => array(
				'Crystal, glass, acrylic and string styles',
				'Divides space while keeping light and air',
				'Made to your width and drop',
				'Ceiling track or decorative rail mounting',
				'For homes, salons, restaurants and events',
			),
			'opt_title'  => 'Bead <em>styles</em>',
			'tiles'      => array(
				array( 'Crystal', 'Clear or tinted crystal strands for sparkle in entrances and dining areas.' ),
				array( 'Glass beads', 'Gold, champagne and amber glass for a warm, luxurious glow.' ),
				array( 'String curtains', 'Fine threads in many colours — soft, light and budget friendly.' ),
				array( 'Custom lengths', 'Cut to finish exactly at the floor or at a chosen height.' ),
			),
			'faqs'       => array(
				array( 'Where are beaded curtains used?', 'As room dividers, doorway curtains, behind sofas or beds, in salons, restaurants, shops and for wedding and event décor.' ),
				array( 'Are beaded curtains heavy?', 'Crystal and glass styles have some weight, so we fix them securely to the ceiling. String curtains are light.' ),
				array( 'Can you make them to any size?', 'Yes. We size the width and drop to the opening.' ),
				array( 'Do you install them?', 'Yes — supply and installation are included in our quotation.' ),
			),
			'related'    => array( 'sheer-curtains', 'cinema-curtains', 'american-style-curtains', 'wave-curtains' ),
		),

		'cinema-curtains'         => array(
			'name'       => 'Cinema &amp; Home Theatre Curtains',
			'parent'     => 'curtains',
			'img'        => 'cinema-curtains',
			'media'      => 'cinema',
			'seo_title'  => 'Cinema & Home Theatre Curtains Dubai | Stage Curtains',
			'seo_desc'   => 'Cinema, home theatre and stage curtains in Dubai: blackout velvet drapes, festoon and swag curtains, motorized tracks. Made to measure. Free site visit.',
			'card'       => 'Velvet blackout drapes, festoon and stage curtains for home cinemas and venues.',
			'kicker'     => 'Curtains · Dubai &amp; UAE',
			'h1'         => '<em>Cinema</em> &amp; home theatre curtains in Dubai',
			'lead'       => 'Total darkness and a sense of occasion. We make velvet blackout drapes, festoon and swag stage curtains for home cinemas, media rooms, schools and event venues.',
			'what_title' => 'Darkness, acoustics <em>and drama</em>',
			'paras'      => array(
				'A home cinema needs fabrics that block light and absorb sound. Heavy velvets with blackout lining reduce reflections, soften echo and frame the screen like a real theatre.',
				'For stages and venues we make festoon (Austrian) curtains, swag-and-tail valances and straight stage drapes that open sideways or lift on cords.',
				'Motorized tracks let you open the screen curtain from your seat, or link it to your media system.',
			),
			'checks'     => array(
				'Velvet and blackout fabrics for dark rooms',
				'Festoon, swag and straight stage curtains',
				'Screen masking and wall drapes',
				'Motorized tracks and remote control',
				'For homes, schools, halls and event venues',
			),
			'opt_title'  => 'Theatre <em>curtain styles</em>',
			'tiles'      => array(
				array( 'Screen curtains', 'Side-opening velvet curtains that reveal the screen.' ),
				array( 'Festoon curtains', 'Austrian-style gathered curtains that lift in soft scallops.' ),
				array( 'Swag valances', 'Classic draped tops for a traditional theatre look.' ),
				array( 'Wall drapes', 'Full-wall fabric to darken rooms and soften acoustics.' ),
			),
			'faqs'       => array(
				array( 'Which fabric is best for a home cinema?', 'Dark velvet or heavy blackout fabrics work best: they absorb light and reduce reflections around the screen.' ),
				array( 'Can cinema curtains be motorized?', 'Yes. Motorized tracks can open the curtains by remote or as part of your media setup.' ),
				array( 'Do you make stage curtains for schools and halls?', 'Yes. Share the stage size and use, and we will recommend styles and fabrics.' ),
				array( 'Do curtains help with acoustics?', 'Heavy fabrics help absorb sound and reduce echo, which improves the listening experience.' ),
			),
			'related'    => array( 'blackout-curtains', 'motorized-curtains', 'american-style-curtains', 'blackout-roller-blinds' ),
		),

		'kids-curtains'           => array(
			'name'       => 'Kids Room Curtains',
			'parent'     => 'curtains',
			'img'        => 'kids-curtains',
			'media'      => 'kids-curtains',
			'seo_title'  => 'Kids Room Curtains Dubai | Nursery Blackout Curtains',
			'seo_desc'   => 'Kids and nursery curtains in Dubai: playful prints, blackout for nap time and child-safe fitting. Made to measure with free home visit and installation.',
			'card'       => 'Playful prints with blackout for nap time — and child-safe fitting.',
			'kicker'     => 'Curtains · Dubai &amp; UAE',
			'h1'         => '<em>Kids room</em> curtains in Dubai',
			'lead'       => 'Cheerful prints, soft pastels and blackout linings for better naps. Our kids’ curtains are made to measure and fitted with child safety in mind.',
			'what_title' => 'Designed for <em>little ones</em>',
			'paras'      => array(
				'Children’s rooms need curtains that look fun and work hard. Blackout linings help babies and toddlers nap during bright afternoons and sleep before sunset in summer.',
				'Pick from florals, stars, animals, stripes and soft plain colours, or combine a patterned curtain with a plain blackout roller blind behind it.',
				'We recommend cordless or tensioned controls and secure fixing so there are no loose cords within a child’s reach.',
			),
			'checks'     => array(
				'Playful prints and soft pastel plains',
				'Blackout linings for nap time',
				'Child-safe, cordless options',
				'Easy-care, washable fabrics',
				'Pairs with blackout roller blinds',
			),
			'opt_title'  => 'Good choices for <em>kids’ rooms</em>',
			'tiles'      => array(
				array( 'Nursery', 'Soft colours and full blackout for daytime naps.' ),
				array( 'Toddlers', 'Fun prints and durable fabrics that are easy to clean.' ),
				array( 'Teens', 'Grown-up colours and textures that last as tastes change.' ),
				array( 'Safety', 'Cordless designs and secure tracks or rods.' ),
			),
			'faqs'       => array(
				array( 'What is the best curtain for a nursery?', 'A blackout-lined curtain, ideally combined with a blackout roller blind, gives the darkest room for naps.' ),
				array( 'Are your kids’ curtains child safe?', 'We recommend cordless or tensioned systems and fit curtains and blinds securely. Ask us about the safest option for your room.' ),
				array( 'Can kids’ curtains be washed?', 'Many of our kids’ fabrics are washable. We advise on care for the fabric you choose.' ),
				array( 'Do you have themed prints?', 'Yes — our catalogues include florals, animals, stars and more. We bring samples to the home visit.' ),
			),
			'related'    => array( 'blackout-curtains', 'blackout-roller-blinds', 'eyelet-curtains', 'printed-blinds' ),
		),

		'hospital-curtains'       => array(
			'name'       => 'Hospital Cubicle Curtains',
			'parent'     => 'curtains',
			'img'        => 'hospital-curtains',
			'media'      => 'hospital-curtains',
			'seo_title'  => 'Hospital Cubicle Curtains Dubai | Clinic Privacy Curtains',
			'seo_desc'   => 'Hospital cubicle and clinic privacy curtains in Dubai and the UAE: ceiling tracks, mesh tops and easy-clean fabrics. Supply and installation. Free site visit.',
			'card'       => 'Cubicle and privacy curtains with ceiling tracks for clinics and hospitals.',
			'kicker'     => 'Curtains · Healthcare · UAE',
			'h1'         => '<em>Hospital cubicle</em> curtains in Dubai',
			'lead'       => 'Privacy curtains and ceiling track systems for hospitals, clinics, dental and beauty centres — supplied, made to size and installed across the UAE.',
			'what_title' => 'Privacy and hygiene <em>for patient areas</em>',
			'paras'      => array(
				'Cubicle curtains divide treatment bays, wards and consultation rooms quickly while giving patients privacy. They hang from ceiling-fixed tracks that follow straight, L-shaped or U-shaped layouts around each bed.',
				'A mesh top panel lets air and light circulate and helps ceiling sprinklers work as designed. Fabrics are chosen for durability and easy cleaning.',
				'We survey the site, plan track layouts with your team, and install with minimal disruption to the facility.',
			),
			'checks'     => array(
				'Straight, L and U-shaped ceiling tracks',
				'Breathable mesh top panels',
				'Durable, easy-clean fabrics',
				'For wards, clinics, dental and beauty centres',
				'Site survey and professional installation',
			),
			'opt_title'  => 'Built for <em>healthcare spaces</em>',
			'tiles'      => array(
				array( 'Track layouts', 'Bent tracks around beds and treatment chairs, ceiling or suspended.' ),
				array( 'Mesh tops', 'Allow airflow and light into each cubicle.' ),
				array( 'Fabrics', 'Durable, cleanable fabrics in calm, clinical colours.' ),
				array( 'Replacement sets', 'Spare curtain sets so you can rotate them for cleaning.' ),
			),
			'faqs'       => array(
				array( 'Do you install hospital curtain tracks?', 'Yes. We survey the space, plan the track layout and install the tracks and curtains.' ),
				array( 'Why do cubicle curtains have a mesh top?', 'The mesh panel allows air and light through and helps ceiling sprinklers reach the cubicle.' ),
				array( 'Can you supply clinics outside Dubai?', 'Yes, we work across the UAE including Abu Dhabi, Sharjah, Ajman and the northern emirates.' ),
				array( 'Can we order spare curtains?', 'Yes. Many facilities keep a second set so curtains can be swapped for cleaning.' ),
			),
			'related'    => array( 'vertical-blinds', 'sunscreen-roller-blinds', 'blackout-roller-blinds', 'logo-sunscreen-blinds' ),
		),

		/* -------------------------------- BLINDS -------------------------------- */

		'blackout-roller-blinds'  => array(
			'name'       => 'Blackout Roller Blinds',
			'parent'     => 'blinds',
			'img'        => 'blackout-roller-blinds',
			'media'      => 'blackout-roller-blinds',
			'seo_title'  => 'Blackout Roller Blinds Dubai | Made to Measure, Motor-Ready',
			'seo_desc'   => 'Blackout roller blinds in Dubai made to measure for bedrooms, nurseries and offices. Chain, spring or motorized, with cassettes. Free home visit & measurement.',
			'card'       => 'Simple, sleek and fully room-darkening — chain, spring or motorized.',
			'kicker'     => 'Blinds · Dubai &amp; UAE',
			'h1'         => '<em>Blackout roller</em> blinds in Dubai',
			'lead'       => 'A clean, minimal blind that rolls away neatly and blocks light completely when down. Perfect for bedrooms, nurseries, media rooms and offices.',
			'what_title' => 'Clean lines, <em>complete darkness</em>',
			'paras'      => array(
				'Blackout roller blinds use a coated or multi-layer fabric that stops light passing through. They roll up tightly into a slim tube or cassette, so the window looks uncluttered when the blind is open.',
				'They are a practical, cost-effective way to darken bedrooms and reduce heat from the strong UAE sun, and they sit neatly inside the window recess or above it.',
				'Combine a blackout roller with sheer curtains or a sunscreen roller on a double bracket for day and night control.',
			),
			'checks'     => array(
				'Blocks light and reduces solar heat',
				'Slim roll, optional cassette or fascia',
				'Chain, spring or motorized control',
				'Inside or outside recess fitting',
				'Double brackets with a sunscreen blind',
			),
			'opt_title'  => 'Options for <em>roller blinds</em>',
			'tiles'      => array(
				array( 'Cassettes', 'A neat cover that hides the roll and reduces light at the top.' ),
				array( 'Controls', 'Chain, spring-assisted or motorized with remote and app.' ),
				array( 'Day &amp; night', 'Pair with a sunscreen roller on one double bracket.' ),
				array( 'Colours', 'Whites, greys, beiges and deep tones to suit any room.' ),
			),
			'faqs'       => array(
				array( 'Do blackout roller blinds let any light in?', 'The fabric blocks light; a little can pass at the edges. Fitting outside the recess or adding side channels reduces this.' ),
				array( 'Can roller blinds be motorized?', 'Yes. Motorized rollers work by remote, app or smart-home system.' ),
				array( 'Blinds or curtains for a bedroom?', 'Many clients combine both: a blackout roller for darkness and curtains for softness. See our guide on curtains vs blinds.' ),
				array( 'Are roller blinds easy to clean?', 'Yes, most can be wiped or dusted. We advise care for the fabric you choose.' ),
			),
			'related'    => array( 'sunscreen-roller-blinds', 'zebra-blinds', 'blackout-curtains', 'roman-blinds' ),
		),

		'sunscreen-roller-blinds' => array(
			'name'       => 'Sunscreen Roller Blinds',
			'parent'     => 'blinds',
			'img'        => 'sunscreen-roller-blinds',
			'media'      => 'sunscreen-roller-blinds',
			'seo_title'  => 'Sunscreen Roller Blinds Dubai | Glare & Heat Control',
			'seo_desc'   => 'Sunscreen roller blinds in Dubai cut glare and heat while keeping the view. Openness options for homes and offices, chain or motorized. Free home visit.',
			'card'       => 'Cut glare and heat while keeping your view — ideal for offices and living rooms.',
			'kicker'     => 'Blinds · Dubai &amp; UAE',
			'h1'         => '<em>Sunscreen roller</em> blinds in Dubai',
			'lead'       => 'Technical mesh fabrics that reduce glare and solar heat while you still see outside. The everyday blind for sunny living rooms, offices and high-rise views.',
			'what_title' => 'See out, <em>keep the heat out</em>',
			'paras'      => array(
				'Sunscreen fabrics are woven with a set openness — the percentage of tiny gaps in the weave. Lower openness blocks more sun and glare; higher openness gives a clearer view.',
				'They protect furniture and floors from fading, make screens easier to read and help air conditioning work less hard — a smart choice for west-facing rooms in the UAE.',
				'Sunscreen rollers suit homes, offices, schools and showrooms, and can be printed with logos for shopfronts.',
			),
			'checks'     => array(
				'Reduces glare and solar heat',
				'Keeps the outside view',
				'Choice of openness and colours',
				'Chain or motorized control',
				'Can be printed with your logo',
			),
			'opt_title'  => 'Choosing a <em>sunscreen fabric</em>',
			'tiles'      => array(
				array( 'Openness 1–3%', 'Maximum glare and heat control for strong west sun.' ),
				array( 'Openness 5%', 'A popular balance between view and sun control.' ),
				array( 'Dark vs light', 'Darker colours give a clearer view out; lighter ones reflect more heat.' ),
				array( 'Logo printing', 'Brand your shop or office windows — see logo sunscreen blinds.' ),
			),
			'faqs'       => array(
				array( 'Do sunscreen blinds give privacy at night?', 'Not fully — when it is dark outside and lights are on inside, people can see in. Add a blackout roller or curtains for night privacy.' ),
				array( 'What openness should I choose?', 'For strong sun and screens, 1–3%. For a clearer view with good sun control, 5%. We bring samples to compare.' ),
				array( 'Are sunscreen blinds good for offices?', 'Yes. They reduce glare on monitors and heat near windows while keeping natural light.' ),
				array( 'Can I have a sunscreen and blackout on one window?', 'Yes, using a double bracket system with two rollers.' ),
			),
			'related'    => array( 'blackout-roller-blinds', 'logo-sunscreen-blinds', 'zebra-blinds', 'vertical-blinds' ),
		),

		'zebra-blinds'            => array(
			'name'       => 'Zebra Blinds',
			'parent'     => 'blinds',
			'img'        => 'zebra-blinds',
			'media'      => 'zebra-blinds',
			'seo_title'  => 'Zebra Blinds Dubai | Day & Night Dual Roller Blinds',
			'seo_desc'   => 'Zebra (day & night) blinds in Dubai: alternating sheer and solid bands for adjustable light and privacy. Made to measure, chain or motorized. Free visit.',
			'card'       => 'Alternating sheer and solid bands — adjust light and privacy in seconds.',
			'kicker'     => 'Blinds · Dubai &amp; UAE',
			'h1'         => '<em>Zebra</em> blinds in Dubai',
			'lead'       => 'Two layers of alternating sheer and solid stripes that slide past each other. Line them up for soft light, offset them for privacy — all in one sleek blind.',
			'what_title' => 'Day and night <em>in one blind</em>',
			'paras'      => array(
				'Zebra blinds (also called day & night or dual blinds) have a continuous loop of fabric with alternating sheer and solid bands. Moving the blind lines the bands up or offsets them.',
				'When the sheer bands align, filtered light comes through; when the solid bands overlap the sheers, you get privacy and much less light. Roll it up completely for a clear window.',
				'They suit living rooms, bedrooms, kitchens and offices, and come in a wide range of textures and colours, including dim-out fabrics.',
			),
			'checks'     => array(
				'Adjustable light and privacy in one blind',
				'Modern, layered look',
				'Cassette head rail for a neat finish',
				'Chain or motorized control',
				'Textured, wood-look and dim-out fabrics',
			),
			'opt_title'  => 'Zebra blind <em>options</em>',
			'tiles'      => array(
				array( 'Band widths', 'Narrow or wide stripes depending on the look you prefer.' ),
				array( 'Dim-out', 'Denser solid bands for bedrooms and media rooms.' ),
				array( 'Cassettes', 'Square or rounded cassettes in white, grey, black or bronze.' ),
				array( 'Motors', 'Remote or app control for wide and hard-to-reach windows.' ),
			),
			'faqs'       => array(
				array( 'Are zebra blinds blackout?', 'Standard zebra blinds are not full blackout, but dim-out zebra fabrics reduce light considerably. For complete darkness choose a blackout roller.' ),
				array( 'Are zebra blinds good for living rooms?', 'Yes. They let you go from bright to private in seconds, which suits busy living spaces.' ),
				array( 'Can zebra blinds be motorized?', 'Yes, with remote, app or smart-home control.' ),
				array( 'How do I clean zebra blinds?', 'Dust regularly and spot-clean gently. We give care advice for your chosen fabric.' ),
			),
			'related'    => array( 'sunscreen-roller-blinds', 'blackout-roller-blinds', 'roman-blinds', 'vertical-blinds' ),
		),

		'roman-blinds'            => array(
			'name'       => 'Roman Blinds',
			'parent'     => 'blinds',
			'img'        => 'roman-blinds',
			'media'      => 'roman-blinds',
			'seo_title'  => 'Roman Blinds Dubai | Fabric Blinds Made to Measure',
			'seo_desc'   => 'Made-to-measure Roman blinds in Dubai: linen, woven, printed and blackout fabrics that fold up neatly. Chain, cordless or motorized. Free home visit.',
			'card'       => 'Soft fabric folds — linen, woven, printed or blackout.',
			'kicker'     => 'Blinds · Dubai &amp; UAE',
			'h1'         => '<em>Roman</em> blinds in Dubai',
			'lead'       => 'Fabric blinds that lift into elegant horizontal folds. Warmer than a roller, neater than a curtain — beautiful in bedrooms, kitchens, studies and bay windows.',
			'what_title' => 'Soft, tailored <em>window dressing</em>',
			'paras'      => array(
				'Roman blinds are made from fabric with supporting rods at the back. Pull the chain and the fabric rises into stacked folds; lower it and it lies flat across the window.',
				'They bring texture and warmth to a room. Choose sheer and linen fabrics for softly filtered light, woven and natural textures for a relaxed look, or blackout linings for bedrooms.',
				'Roman blinds can sit inside the recess for a built-in look or above the window to make it feel larger.',
			),
			'checks'     => array(
				'Sheer, linen, woven, printed and blackout fabrics',
				'Inside or outside recess fitting',
				'Chain, cordless or motorized operation',
				'Layer under curtains for a finished look',
				'Made to your exact measurements',
			),
			'opt_title'  => 'Roman blind <em>fabrics</em>',
			'tiles'      => array(
				array( 'Sheer &amp; linen', 'Filtered daylight with a soft, airy feel.' ),
				array( 'Woven &amp; natural', 'Textured weaves for warmth and character.' ),
				array( 'Printed', 'Florals, geometrics and statement prints — or your own design.' ),
				array( 'Blackout', 'Blackout linings for bedrooms and nurseries.' ),
			),
			'faqs'       => array(
				array( 'Are Roman blinds good for bedrooms?', 'Yes. With a blackout lining, Roman blinds darken the room while adding softness.' ),
				array( 'Can Roman blinds be used in kitchens?', 'Yes, with easy-care fabrics away from direct heat and splashes.' ),
				array( 'What is the difference between Roman blinds and roller blinds?', 'Roman blinds fold up in soft fabric layers; roller blinds roll around a tube. Romans are softer and more decorative; rollers are slimmer and simpler.' ),
				array( 'Can Roman blinds be motorized?', 'Yes, motor options are available for Roman blinds.' ),
			),
			'related'    => array( 'roman-curtains', 'zebra-blinds', 'bamboo-blinds', 'printed-blinds' ),
		),

		'vertical-blinds'         => array(
			'name'       => 'Vertical Blinds',
			'parent'     => 'blinds',
			'img'        => 'vertical-blinds',
			'media'      => 'vertical-blinds',
			'seo_title'  => 'Vertical Blinds Dubai | Office & Sliding Door Blinds',
			'seo_desc'   => 'Vertical blinds in Dubai for offices, sliding doors and wide windows. Rotating fabric or PVC slats for precise light control. Made to measure, free visit.',
			'card'       => 'Rotating vertical slats for wide windows, sliding doors and offices.',
			'kicker'     => 'Blinds · Dubai &amp; UAE',
			'h1'         => '<em>Vertical</em> blinds in Dubai',
			'lead'       => 'Vertical slats that rotate to angle the light and slide aside to open the window. A practical, durable choice for offices, sliding doors and wide glazing.',
			'what_title' => 'Precise control <em>for wide windows</em>',
			'paras'      => array(
				'Vertical blinds hang from a head rail as individual slats (louvres). Rotate them to direct daylight and privacy, or draw them fully to one side or split them in the middle.',
				'They are hard-wearing and easy to maintain, which is why they are popular in offices, schools, clinics and on patio and balcony sliding doors.',
				'Choose from fabric, blackout and PVC slats in many colours, cut to the exact height of your window or door.',
			),
			'checks'     => array(
				'Rotate slats for exact light control',
				'Ideal for sliding doors and wide windows',
				'Fabric, blackout and PVC slats',
				'Durable and easy to maintain',
				'Popular for offices and clinics',
			),
			'opt_title'  => 'Vertical blind <em>options</em>',
			'tiles'      => array(
				array( 'Slat widths', 'Standard slat widths to suit both homes and offices.' ),
				array( 'Blackout slats', 'For meeting rooms, bedrooms and presentation spaces.' ),
				array( 'Stack options', 'Stack left, right or split in the centre for doors.' ),
				array( 'Wand or cord', 'Simple manual controls or motorization for large runs.' ),
			),
			'faqs'       => array(
				array( 'Are vertical blinds good for sliding doors?', 'Yes. They stack neatly to one side so you can walk through, and slats rotate for privacy.' ),
				array( 'Are vertical blinds suitable for offices?', 'Yes. They control glare on screens and are durable for daily use.' ),
				array( 'Can damaged slats be replaced?', 'Individual slats can usually be replaced without changing the whole blind.' ),
				array( 'Do you have blackout vertical blinds?', 'Yes, blackout fabrics are available for vertical blinds.' ),
			),
			'related'    => array( 'sunscreen-roller-blinds', 'aluminium-venetian-blinds', 'zebra-blinds', 'hospital-curtains' ),
		),

		'wooden-blinds'           => array(
			'name'       => 'Wooden Venetian Blinds',
			'parent'     => 'blinds',
			'img'        => 'wooden-blinds',
			'media'      => 'wooden-blinds',
			'seo_title'  => 'Wooden Blinds Dubai | 50mm & 25mm Wooden Venetian Blinds',
			'seo_desc'   => 'Wooden venetian blinds in Dubai: 50mm and 25mm real wood and faux-wood slats, tapes or strings, made to measure. Free home visit and installation.',
			'card'       => 'Warm 50mm or 25mm wooden slats with ladder tapes or strings.',
			'kicker'     => 'Blinds · Dubai &amp; UAE',
			'h1'         => '<em>Wooden venetian</em> blinds in Dubai',
			'lead'       => 'Natural warmth and precise light control. Tilt the slats to angle the sun, raise them to open the view — a timeless choice for living rooms, bedrooms and studies.',
			'what_title' => 'Natural texture, <em>tailored control</em>',
			'paras'      => array(
				'Wooden venetian blinds have horizontal slats that tilt and lift. They bring the warmth of timber into a room and suit everything from minimalist apartments to classic villas.',
				'Choose 50mm slats for a bold, architectural look on larger windows, or 25mm slats for smaller windows and a finer appearance. Decorative ladder tapes add a tailored finish.',
				'For humid areas, faux-wood slats give the same look with extra moisture resistance.',
			),
			'checks'     => array(
				'50mm and 25mm slat sizes',
				'Real wood and faux-wood options',
				'Strings or decorative ladder tapes',
				'Many stains, whites and painted colours',
				'Tilt for privacy, lift for view',
			),
			'opt_title'  => 'Wood <em>finishes &amp; details</em>',
			'tiles'      => array(
				array( '50mm slats', 'Wider slats for a contemporary, architectural look.' ),
				array( '25mm slats', 'Finer slats for small windows and doors.' ),
				array( 'Tapes', 'Cloth ladder tapes in matching or contrast colours.' ),
				array( 'Faux wood', 'Moisture-tolerant slats for kitchens and bathrooms.' ),
			),
			'faqs'       => array(
				array( 'Are wooden blinds suitable for Dubai’s climate?', 'Yes, in living areas and bedrooms. For humid rooms like bathrooms we recommend faux-wood slats.' ),
				array( '50mm or 25mm slats?', '50mm slats suit larger windows and modern rooms; 25mm suits smaller windows. We bring both to compare.' ),
				array( 'Can wooden blinds be motorized?', 'Motorized options are available for some wooden blind systems — ask during your visit.' ),
				array( 'How do I clean wooden blinds?', 'Dust slats regularly with a soft cloth or duster; avoid soaking real wood.' ),
			),
			'related'    => array( 'aluminium-venetian-blinds', 'bamboo-blinds', 'roman-blinds', 'zebra-blinds' ),
		),

		'aluminium-venetian-blinds' => array(
			'name'       => 'Aluminium Venetian Blinds',
			'parent'     => 'blinds',
			'img'        => 'aluminium-venetian-blinds',
			'media'      => 'aluminium-venetian-blinds',
			'seo_title'  => 'Aluminium Venetian Blinds Dubai | 25mm Metal Blinds',
			'seo_desc'   => 'Aluminium venetian blinds in Dubai: 25mm metal slats, perforated options, moisture resistant for kitchens, bathrooms and offices. Made to measure, free visit.',
			'card'       => 'Slim 25mm metal slats — durable, moisture resistant and precise.',
			'kicker'     => 'Blinds · Dubai &amp; UAE',
			'h1'         => '<em>Aluminium venetian</em> blinds in Dubai',
			'lead'       => 'Slim, durable metal slats with precise tilt control. Aluminium venetians are moisture resistant and easy to clean — ideal for kitchens, bathrooms and offices.',
			'what_title' => 'Slim, tough <em>and practical</em>',
			'paras'      => array(
				'Aluminium venetian blinds use lightweight 25mm metal slats that tilt to control light and privacy. They are robust, simple to clean and resist humidity better than wood.',
				'Perforated slats let some light and view through even when closed, while solid slats give more privacy. Colours range from clean whites and silvers to black, champagne and metallics.',
				'They fit neatly inside the window recess and are a long-lasting choice for busy rooms and workplaces.',
			),
			'checks'     => array(
				'Moisture resistant and easy to clean',
				'Solid or perforated 25mm slats',
				'Whites, metallics, black and colours',
				'Neat inside-recess fitting',
				'Great for kitchens, bathrooms and offices',
			),
			'opt_title'  => 'Aluminium <em>options</em>',
			'tiles'      => array(
				array( 'Perforated', 'Micro-holes let light through when closed.' ),
				array( 'Colours', 'From brilliant white to brushed metallics and matte black.' ),
				array( 'Controls', 'Tilt wand and lift cord, or motorized options.' ),
				array( 'Commercial', 'Durable for offices, schools and clinics.' ),
			),
			'faqs'       => array(
				array( 'Are aluminium blinds good for bathrooms?', 'Yes. Aluminium resists moisture and is easy to wipe clean.' ),
				array( 'Do aluminium blinds get hot in the sun?', 'Metal slats reflect much of the sun. Lighter colours reflect more heat.' ),
				array( 'What does perforated mean?', 'Tiny holes in the slats let a little light and view through even when the blind is closed.' ),
				array( 'Are they suitable for offices?', 'Yes — they are durable, tidy and give precise glare control.' ),
			),
			'related'    => array( 'wooden-blinds', 'vertical-blinds', 'sunscreen-roller-blinds', 'zebra-blinds' ),
		),

		'bamboo-blinds'           => array(
			'name'       => 'Bamboo Blinds',
			'parent'     => 'blinds',
			'img'        => 'bamboo-blinds',
			'media'      => 'bamboo-blinds',
			'seo_title'  => 'Bamboo Blinds Dubai | Indoor & Outdoor Natural Blinds',
			'seo_desc'   => 'Bamboo blinds in Dubai for indoor rooms, terraces, pergolas and majlis. Natural textures, roller and Roman styles, made to measure. Free site visit.',
			'card'       => 'Natural bamboo for terraces, pergolas, sunrooms and relaxed interiors.',
			'kicker'     => 'Blinds · Dubai &amp; UAE',
			'h1'         => '<em>Bamboo</em> blinds in Dubai',
			'lead'       => 'Warm, natural textures that filter sunlight beautifully. Bamboo blinds bring a relaxed, resort feel to sunrooms, terraces, pergolas and garden majlis.',
			'what_title' => 'Natural shade, <em>indoors and out</em>',
			'paras'      => array(
				'Bamboo blinds are woven from natural bamboo slats or reeds. They filter light into a warm, dappled glow and add organic texture to modern and traditional spaces.',
				'Indoors, they work as roller or Roman-style blinds in living rooms and sunrooms. Outdoors, heavier bamboo blinds give shade and privacy on terraces, balconies and pergolas.',
				'Add a privacy or blackout lining to indoor bamboo blinds when you need more coverage.',
			),
			'checks'     => array(
				'Natural, warm texture',
				'Indoor and outdoor styles',
				'Roller and Roman-fold options',
				'Optional privacy or blackout lining',
				'Shade for terraces, pergolas and majlis',
			),
			'opt_title'  => 'Bamboo <em>styles</em>',
			'tiles'      => array(
				array( 'Roller bamboo', 'Rolls up neatly — simple and practical.' ),
				array( 'Roman bamboo', 'Soft folds for a tailored, natural look.' ),
				array( 'Outdoor bamboo', 'Heavier blinds for terraces and pergolas.' ),
				array( 'Linings', 'Add privacy or blackout to indoor bamboo blinds.' ),
			),
			'faqs'       => array(
				array( 'Can bamboo blinds be used outdoors in the UAE?', 'Yes, outdoor bamboo blinds give shade on terraces and pergolas. Natural materials weather over time; we advise on care.' ),
				array( 'Do bamboo blinds give privacy?', 'They filter light and give partial privacy. Add a lining for more privacy, especially at night.' ),
				array( 'Are bamboo blinds made to measure?', 'Yes, we make them to the width and drop you need.' ),
				array( 'Can bamboo blinds be combined with curtains?', 'Yes — sheer or linen curtains over bamboo blinds create a soft, layered look.' ),
			),
			'related'    => array( 'roman-blinds', 'wooden-blinds', 'sunscreen-roller-blinds', 'sheer-curtains' ),
		),

		'printed-blinds'          => array(
			'name'       => 'Custom Printed Blinds',
			'parent'     => 'blinds',
			'img'        => 'printed-blinds',
			'media'      => 'printed-blinds',
			'seo_title'  => 'Custom Printed Blinds Dubai | Photo & Pattern Roller Blinds',
			'seo_desc'   => 'Custom printed blinds in Dubai: print photos, patterns or artwork on roller and Roman blinds for homes, kids rooms and businesses. Free home visit.',
			'card'       => 'Your photo, pattern or artwork printed on roller and Roman blinds.',
			'kicker'     => 'Blinds · Dubai &amp; UAE',
			'h1'         => '<em>Custom printed</em> blinds in Dubai',
			'lead'       => 'Turn a window into a feature. We print photos, patterns and artwork onto roller and Roman blinds — for kids’ rooms, kitchens, offices, cafés and showrooms.',
			'what_title' => 'A window that <em>tells your story</em>',
			'paras'      => array(
				'Custom printed blinds start with any image: a family photo, a landscape, a pattern, your artwork or a brand graphic. We print it onto blind fabric and make it up to your window size.',
				'They are popular in children’s rooms, kitchens and playrooms at home, and in cafés, salons, clinics and offices where a window can carry a message.',
				'Prints are available on light-filtering, dim-out and blackout fabrics. Download our custom print on fabric brochure from the <a href="/catalogue/">catalogues page</a>.',
			),
			'checks'     => array(
				'Print photos, patterns or artwork',
				'Roller and Roman blind styles',
				'Light-filtering, dim-out or blackout bases',
				'For homes, kids’ rooms and businesses',
				'Proof checked before printing',
			),
			'opt_title'  => 'How custom printing <em>works</em>',
			'tiles'      => array(
				array( 'Send your image', 'Share a high-resolution photo or design on WhatsApp.' ),
				array( 'We prepare a proof', 'We size and position the design to your window.' ),
				array( 'Choose the fabric', 'Light-filtering, dim-out or blackout base fabric.' ),
				array( 'Print &amp; install', 'We print, make up and install the blind.' ),
			),
			'faqs'       => array(
				array( 'What image quality do I need?', 'The higher the resolution, the better. Send the original file and we will check it fits the blind size.' ),
				array( 'Can printed blinds be blackout?', 'Yes, we can print on blackout base fabric.' ),
				array( 'Can I print my company logo?', 'Yes — see our logo sunscreen blinds for branded shop and office windows.' ),
				array( 'Will the print fade?', 'Prints are made for indoor use. Like all fabrics, very strong direct sun can fade colours over time; we advise on placement.' ),
			),
			'related'    => array( 'logo-sunscreen-blinds', 'kids-curtains', 'roman-blinds', 'blackout-roller-blinds' ),
		),

		'logo-sunscreen-blinds'   => array(
			'name'       => 'Logo Sunscreen Blinds',
			'parent'     => 'blinds',
			'img'        => 'logo-sunscreen-blinds',
			'media'      => 'logo-printed-sunscreen',
			'seo_title'  => 'Logo Printed Sunscreen Blinds Dubai | Branded Shop Blinds',
			'seo_desc'   => 'Customised logo sunscreen blinds in Dubai: branded roller blinds for shops, restaurants, offices and showrooms. Cut glare and advertise. Free site visit.',
			'card'       => 'Branded roller blinds that cut glare and promote your business.',
			'kicker'     => 'Blinds · Commercial · UAE',
			'h1'         => '<em>Logo sunscreen</em> blinds in Dubai',
			'lead'       => 'Sun control that works as signage. We print your logo and brand graphics onto sunscreen roller blinds for shopfronts, restaurants, offices and showrooms.',
			'what_title' => 'Shade your space, <em>show your brand</em>',
			'paras'      => array(
				'Logo sunscreen blinds combine technical sunscreen fabric with printed branding. Inside, they cut glare and heat for staff and customers; outside, they turn windows into branded signage.',
				'They are a smart upgrade for retail units, cafés, clinics, gyms and offices in malls, high streets and business parks across the UAE.',
				'Send us your logo file and window sizes and we will prepare a visual proof before production.',
			),
			'checks'     => array(
				'Printed logos and brand graphics',
				'Glare and heat control for staff and customers',
				'Shops, restaurants, offices and showrooms',
				'Proof approved before printing',
				'Chain or motorized operation',
			),
			'opt_title'  => 'For <em>businesses</em>',
			'tiles'      => array(
				array( 'Retail', 'Branded shopfronts that still let customers see in.' ),
				array( 'Food &amp; beverage', 'Comfortable dining with less glare and visible branding.' ),
				array( 'Offices', 'Glare control with your logo for meeting rooms and receptions.' ),
				array( 'Multi-site', 'Consistent branded blinds across several locations.' ),
			),
			'faqs'       => array(
				array( 'What file do you need for my logo?', 'A vector file (AI, EPS, PDF or SVG) is best. High-resolution PNG can also work.' ),
				array( 'Can people still see through the blind?', 'Sunscreen fabric keeps some view through it; the printed areas are more solid.' ),
				array( 'Do you work outside Dubai?', 'Yes, we serve businesses across the UAE.' ),
				array( 'Can you match brand colours?', 'We print closely to your brand colours and share a proof before production.' ),
			),
			'related'    => array( 'printed-blinds', 'sunscreen-roller-blinds', 'vertical-blinds', 'blackout-roller-blinds' ),
		),
	);
}
