<?php
/**
 * One-shot site installer (admins only).
 *
 * POST /wp-json/dce/v1/install with {"gz": "<base64 gzip JSON>"} where the
 * JSON holds pages, menus and footer widgets generated by site-build/build.py.
 * Uses core APIs (wp_insert_post, wp_update_nav_menu_item, widget options),
 * so everything it creates is ordinary, fully editable WordPress content.
 * Re-running updates the same pages instead of duplicating them.
 *
 * @package Dubai_Curtain_Experts
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Register the installer route.
 */
function dce_register_install_route() {
	register_rest_route(
		'dce/v1',
		'/install',
		array(
			'methods'             => 'POST',
			'permission_callback' => function () {
				return current_user_can( 'manage_options' );
			},
			'callback'            => 'dce_rest_install',
		)
	);
}
add_action( 'rest_api_init', 'dce_register_install_route' );

/**
 * Installer callback.
 *
 * @param WP_REST_Request $request Request.
 * @return array|WP_Error
 */
function dce_rest_install( $request ) {
	$raw  = base64_decode( (string) $request->get_param( 'gz' ), true );
	$json = $raw ? gzdecode( $raw ) : false;
	$data = $json ? json_decode( $json, true ) : null;
	if ( ! is_array( $data ) ) {
		return new WP_Error( 'dce_bad_payload', 'Payload could not be decoded.', array( 'status' => 400 ) );
	}

	$ids = array();
	$out = array( 'pages' => array() );

	/* ---------------------------------------------------------- pages */
	foreach ( (array) $data['pages'] as $order => $pg ) {
		$parent = ( ! empty( $pg['parent'] ) && isset( $ids[ $pg['parent'] ] ) ) ? $ids[ $pg['parent'] ] : 0;
		$id     = 0;
		if ( ! empty( $pg['existing_id'] ) && get_post( (int) $pg['existing_id'] ) ) {
			$id = (int) $pg['existing_id'];
		} else {
			$found = get_page_by_path( trim( $pg['path'], '/' ), OBJECT, 'page' );
			if ( $found ) {
				$id = (int) $found->ID;
			}
		}

		$postarr = array(
			'post_type'    => 'page',
			'post_status'  => 'publish',
			'post_title'   => $pg['title'],
			'post_name'    => $pg['slug'],
			'post_parent'  => $parent,
			'post_excerpt' => $pg['excerpt'],
			'post_content' => $pg['content'],
			'menu_order'   => (int) $order,
			'comment_status' => 'closed',
		);
		if ( $id ) {
			$postarr['ID'] = $id;
			$result        = wp_update_post( wp_slash( $postarr ), true );
		} else {
			$result = wp_insert_post( wp_slash( $postarr ), true );
		}
		if ( is_wp_error( $result ) ) {
			$out['pages'][ $pg['key'] ] = array( 'error' => $result->get_error_message() );
			continue;
		}
		$id                = (int) $result;
		$ids[ $pg['key'] ] = $id;
		update_post_meta( $id, '_wp_page_template', 'page-templates/landing.php' );
		if ( ! empty( $pg['featured_media'] ) ) {
			set_post_thumbnail( $id, (int) $pg['featured_media'] );
		}
		$out['pages'][ $pg['key'] ] = array(
			'id'   => $id,
			'link' => get_permalink( $id ),
		);
	}

	/* ----------------------------------------------------- front page */
	if ( isset( $ids['home'] ) ) {
		update_option( 'show_on_front', 'page' );
		update_option( 'page_on_front', $ids['home'] );
	}

	/* ---------------------------------------------------------- menus */
	$locations = get_theme_mod( 'nav_menu_locations', array() );
	foreach ( (array) $data['menus'] as $menu ) {
		$obj     = wp_get_nav_menu_object( $menu['name'] );
		$menu_id = $obj ? (int) $obj->term_id : (int) wp_create_nav_menu( $menu['name'] );
		if ( ! $menu_id || is_wp_error( $menu_id ) ) {
			continue;
		}
		foreach ( (array) wp_get_nav_menu_items( $menu_id ) as $old ) {
			wp_delete_post( $old->ID, true );
		}
		$pos = 1;
		foreach ( (array) $menu['items'] as $item ) {
			$parent_item = dce_install_menu_item( $menu_id, $item, 0, $pos++, $ids );
			foreach ( isset( $item['children'] ) ? (array) $item['children'] : array() as $child ) {
				dce_install_menu_item( $menu_id, $child, $parent_item, $pos++, $ids );
			}
		}
		$locations[ $menu['location'] ] = $menu_id;
		$out['menus'][ $menu['location'] ] = $menu_id;
	}
	set_theme_mod( 'nav_menu_locations', $locations );

	/* -------------------------------------------------- footer widgets */
	if ( ! empty( $data['widgets'] ) ) {
		$blocks   = get_option( 'widget_block', array() );
		$sidebars = get_option( 'sidebars_widgets', array() );
		$next     = 900;
		foreach ( (array) $data['widgets'] as $sidebar => $contents ) {
			$sidebars[ $sidebar ] = array();
			foreach ( (array) $contents as $html ) {
				while ( isset( $blocks[ $next ] ) ) {
					$next++;
				}
				$blocks[ $next ]        = array( 'content' => dce_install_links( $html, $ids ) );
				$sidebars[ $sidebar ][] = 'block-' . $next;
				$next++;
			}
		}
		update_option( 'widget_block', $blocks );
		update_option( 'sidebars_widgets', $sidebars );
		$out['widgets'] = 'ok';
	}

	flush_rewrite_rules( false );
	return $out;
}

/**
 * Add one menu item (page by key, or custom URL).
 *
 * @param int   $menu_id Menu.
 * @param array $item    {key|url, title}.
 * @param int   $parent  Parent menu item ID.
 * @param int   $pos     Position.
 * @param array $ids     Page key => ID.
 * @return int Menu item ID.
 */
function dce_install_menu_item( $menu_id, $item, $parent, $pos, $ids ) {
	$args = array(
		'menu-item-title'     => $item['title'],
		'menu-item-status'    => 'publish',
		'menu-item-parent-id' => $parent,
		'menu-item-position'  => $pos,
	);
	if ( ! empty( $item['key'] ) && isset( $ids[ $item['key'] ] ) ) {
		$args['menu-item-object-id'] = $ids[ $item['key'] ];
		$args['menu-item-object']    = 'page';
		$args['menu-item-type']      = 'post_type';
	} else {
		$args['menu-item-url']  = $item['url'];
		$args['menu-item-type'] = 'custom';
		if ( ! empty( $item['new_tab'] ) ) {
			$args['menu-item-target'] = '_blank';
		}
	}
	return (int) wp_update_nav_menu_item( $menu_id, 0, $args );
}

/**
 * Replace {{page:key}} placeholders in widget HTML with permalinks.
 *
 * @param string $html HTML.
 * @param array  $ids  Page key => ID.
 * @return string
 */
function dce_install_links( $html, $ids ) {
	return preg_replace_callback(
		'/\{\{page:([a-z0-9-]+)\}\}/',
		function ( $m ) use ( $ids ) {
			return isset( $ids[ $m[1] ] ) ? get_permalink( $ids[ $m[1] ] ) : home_url( '/' );
		},
		$html
	);
}
